-- ========================================================================
-- Auto-generated by generate-scenarios-sql.mjs
-- 2026-06-16T15:50:26.721Z
-- ========================================================================

-- ──────────────────────────────────────────────────────────────────────
-- Source : 01_phone-restaurant-reservation.json
-- Group  : daily-life  (daily)
-- Langs  : en, ja
-- ──────────────────────────────────────────────────────────────────────

-- scenario_groups
INSERT INTO scenario_groups (id, slug, category) VALUES
  ('00000000-0000-0000-0000-000000000003', 'daily-life', 'daily')
ON CONFLICT (id) DO NOTHING;

-- scenarios
INSERT INTO scenarios (id, group_id, language_id, title, description, level, type, icon, sort_order) VALUES
  (
    '00000000-0000-0000-0003-000000000001',
    '00000000-0000-0000-0000-000000000003',
    'en',
    'Restaurant Reservation by Phone',
    'Call a restaurant to book a table. Handle fully-booked slots, suggest an alternative time, and make special requests for a birthday dinner.',
    'intermediate', 'scripted', '📞', 1
  ),
  (
    '00000000-0000-0000-0003-000000000002',
    '00000000-0000-0000-0000-000000000003',
    'ja',
    '電話でレストランを予約する',
    '電話でレストランの席を予約します。満席の場合の対応、代替時間の調整、誕生日などの特別リクエストも練習できます。',
    'intermediate', 'scripted', '📞', 1
  )
ON CONFLICT (id) DO NOTHING;

-- scenario_lines: en — Restaurant Reservation by Phone
DELETE FROM scenario_lines WHERE scenario_id = '00000000-0000-0000-0003-000000000001';
INSERT INTO scenario_lines (scenario_id, language_id, sort_order, speaker, text, translation) VALUES
  ('00000000-0000-0000-0003-000000000001', 'en', 1, 'partner', 'Thank you for calling Bella Italia. How can I help you today?', 'Cảm ơn bạn đã gọi đến Bella Italia. Tôi có thể giúp gì cho bạn?'),
  ('00000000-0000-0000-0003-000000000001', 'en', 2, 'user', 'Hi, I''d like to make a reservation for this Saturday evening, please.', 'Xin chào, tôi muốn đặt bàn cho tối thứ Bảy tuần này.'),
  ('00000000-0000-0000-0003-000000000001', 'en', 3, 'partner', 'Of course! How many people will be dining, and what time were you thinking?', 'Tất nhiên! Sẽ có bao nhiêu người và bạn muốn đặt lúc mấy giờ?'),
  ('00000000-0000-0000-0003-000000000001', 'en', 4, 'user', 'There''ll be four of us. Do you have anything available around seven o''clock?', 'Sẽ có bốn người. Khoảng bảy giờ còn bàn không?'),
  ('00000000-0000-0000-0003-000000000001', 'en', 5, 'partner', 'Let me check... I''m sorry, seven o''clock is fully booked. We do have availability at seven thirty — would that work for you?', 'Để tôi xem... Xin lỗi, bảy giờ đã hết bàn. Nhưng còn bàn lúc bảy giờ rưỡi — bạn có thể không?'),
  ('00000000-0000-0000-0003-000000000001', 'en', 6, 'user', 'Seven thirty is fine. It''s actually a birthday dinner, so could we have a quiet table if possible?', 'Bảy rưỡi được. Thật ra đây là bữa tối sinh nhật, nếu có thể cho chúng tôi bàn yên tĩnh được không?'),
  ('00000000-0000-0000-0003-000000000001', 'en', 7, 'partner', 'How lovely! I''ll make a note of that. May I take your name, please?', 'Thật đặc biệt! Tôi sẽ ghi chú lại. Cho tôi xin tên bạn?'),
  ('00000000-0000-0000-0003-000000000001', 'en', 8, 'user', 'It''s Minh Nguyen. That''s N-G-U-Y-E-N.', 'Tên tôi là Minh Nguyễn. Đánh vần là N-G-U-Y-E-N.'),
  ('00000000-0000-0000-0003-000000000001', 'en', 9, 'partner', 'Thank you, Mr. Nguyen. Could I also get a contact number in case we need to reach you?', 'Cảm ơn anh Nguyễn. Cho tôi xin số điện thoại liên lạc?'),
  ('00000000-0000-0000-0003-000000000001', 'en', 10, 'user', 'Sure. It''s zero-nine-zero, one-two-three-four, five-six-seven-eight.', 'Được. Số của tôi là 090-1234-5678.'),
  ('00000000-0000-0000-0003-000000000001', 'en', 11, 'partner', 'Perfect. To confirm: a table for four at seven thirty this Saturday, under Nguyen, for a birthday. Your reservation number is B-2947.', 'Tuyệt. Xác nhận: bàn cho bốn người lúc bảy rưỡi tối thứ Bảy, tên Nguyễn, dịp sinh nhật. Mã đặt bàn là B-2947.'),
  ('00000000-0000-0000-0003-000000000001', 'en', 12, 'user', 'Great, thank you so much. See you on Saturday!', 'Tuyệt, cảm ơn bạn rất nhiều. Hẹn gặp lại thứ Bảy!');

-- scenario_lines: ja — 電話でレストランを予約する
DELETE FROM scenario_lines WHERE scenario_id = '00000000-0000-0000-0003-000000000002';
INSERT INTO scenario_lines (scenario_id, language_id, sort_order, speaker, text, translation, furigana, romaji) VALUES
  ('00000000-0000-0000-0003-000000000002', 'ja', 1, 'partner', 'はい、ベラ・イタリアでございます。', 'Vâng, đây là nhà hàng Bella Italia.', 'はい、ベラ・イタリアでございます。', 'Hai, Bera-Itaria de gozaimasu.'),
  ('00000000-0000-0000-0003-000000000002', 'ja', 2, 'user', 'あの、今週の土曜日の夜に予約したいのですが。', 'Xin lỗi, tôi muốn đặt bàn cho tối thứ Bảy tuần này ạ.', 'あの、こんしゅうのどようびのよるによやくしたいのですが。', 'Ano, konshū no doyōbi no yoru ni yoyaku shitai no desu ga.'),
  ('00000000-0000-0000-0003-000000000002', 'ja', 3, 'partner', 'ありがとうございます。何名様で、何時頃をご希望でしょうか？', 'Cảm ơn bạn. Bao nhiêu người và mấy giờ thì bạn muốn?', 'ありがとうございます。なんめいさまで、なんじごろをごきぼうでしょうか？', 'Arigatō gozaimasu. Nan-mei-sama de, nan-ji goro wo go-kibō deshō ka?'),
  ('00000000-0000-0000-0003-000000000002', 'ja', 4, 'user', '四名です。夜の七時頃は空いていますか？', 'Bốn người ạ. Khoảng 7 giờ tối còn bàn không?', 'よんめいです。よるのしちじごろはあいていますか？', 'Yon-mei desu. Yoru no shichi-ji goro wa aite imasu ka?'),
  ('00000000-0000-0000-0003-000000000002', 'ja', 5, 'partner', '申し訳ございません。七時は満席でございます。七時半でしたらご用意できますが、いかがでしょうか？', 'Xin lỗi, 7 giờ đã kín bàn rồi. Còn 7 giờ 30 thì được, bạn thấy thế nào?', 'もうしわけございません。しちじはまんせきでございます。しちじはんでしたらごよういできますが、いかがでしょうか？', 'Mōshiwake gozaimasu. Shichi-ji wa manseki de gozaimasu. Shichi-ji-han deshitara go-yōi dekimasu ga, ikaga deshō ka?'),
  ('00000000-0000-0000-0003-000000000002', 'ja', 6, 'user', '七時半で大丈夫です。実は誕生日のお祝いなので、できれば静かな席をお願いできますか？', '7 giờ 30 được ạ. Thật ra đây là bữa tiệc sinh nhật, nếu có thể xin cho chỗ yên tĩnh được không?', 'しちじはんでだいじょうぶです。じつはたんじょうびのおいわいなので、できればしずかなせきをおねがいできますか？', 'Shichi-ji-han de daijōbu desu. Jitsu wa tanjōbi no o-iwai nanode, dekireba shizuka na seki wo onegai dekimasu ka?'),
  ('00000000-0000-0000-0003-000000000002', 'ja', 7, 'partner', 'かしこまりました。お誕生日のお祝い、おめでとうございます！お名前をいただけますか？', 'Vâng, tôi hiểu. Xin chúc mừng sinh nhật! Cho tôi xin tên của bạn?', 'かしこまりました。おたんじょうびのおいわい、おめでとうございます！おなまえをいただけますか？', 'Kashikomarimashita. O-tanjōbi no o-iwai, o-medeto gozaimasu! O-namae wo itadakemasu ka?'),
  ('00000000-0000-0000-0003-000000000002', 'ja', 8, 'user', 'グエン・ミンと申します。', 'Tên tôi là Nguyen Minh ạ.', 'グエン・ミンともうします。', 'Guen Min to mōshimasu.'),
  ('00000000-0000-0000-0003-000000000002', 'ja', 9, 'partner', 'グエン・ミン様、ありがとうございます。ご連絡先の電話番号をお聞かせいただけますか？', 'Cảm ơn anh/chị Nguyen Minh. Cho tôi xin số điện thoại liên lạc được không?', 'グエン・ミンさま、ありがとうございます。ごれんらくさきのでんわばんごうをおきかせいただけますか？', 'Guen Min-sama, arigatō gozaimasu. Go-renrakusaki no denwa-bangō wo o-kikase itadakemasu ka?'),
  ('00000000-0000-0000-0003-000000000002', 'ja', 10, 'user', 'はい、○九○の一二三四の五六七八です。', 'Vâng, số là 090-1234-5678 ạ.', 'はい、まるきゅうまるのいちにさんしのごろくしちはちです。', 'Hai, maru-kyū-maru no ichi-ni-san-shi no go-roku-shichi-hachi desu.'),
  ('00000000-0000-0000-0003-000000000002', 'ja', 11, 'partner', 'ありがとうございます。土曜日の19時半、グエン・ミン様で4名様、誕生日のお祝いにてご予約を承りました。予約番号はB-2947でございます。', 'Cảm ơn bạn. Tôi xác nhận: thứ Bảy 19:30, tên Nguyen Minh, 4 người, dịp sinh nhật. Mã đặt bàn là B-2947.', 'ありがとうございます。どようびのじゅうくじはん、グエン・ミンさまでよんめいさま、たんじょうびのおいわいにてごよやくをうけたまわりました。よやくばんごうはB-2947でございます。', 'Arigatō gozaimasu. Doyōbi no jū-ku-ji-han, Guen Min-sama de yon-mei-sama, tanjōbi no o-iwai nite go-yoyaku wo uketamawarimashita. Yoyaku-bangō wa B-2947 de gozaimasu.'),
  ('00000000-0000-0000-0003-000000000002', 'ja', 12, 'user', 'ありがとうございます。土曜日によろしくお願いします。失礼します。', 'Cảm ơn bạn. Hẹn gặp lại thứ Bảy. Tạm biệt.', 'ありがとうございます。どようびによろしくおねがいします。しつれいします。', 'Arigatō gozaimasu. Doyōbi ni yoroshiku onegai shimasu. Shitsurei shimasu.');
