-- ========================================================================
-- Auto-generated by generate-scenarios-sql.mjs
-- 2026-06-16T23:50:09.857Z
-- ========================================================================

-- ──────────────────────────────────────────────────────────────────────
-- Source : 01_receive-parcel.json
-- Group  : postal-delivery  (daily)
-- Langs  : en, ja
-- ──────────────────────────────────────────────────────────────────────

-- scenario_groups
INSERT INTO scenario_groups (id, slug, category) VALUES
  ('00000000-0000-0000-0000-000000000005', 'postal-delivery', 'daily')
ON CONFLICT (id) DO NOTHING;

-- scenarios
INSERT INTO scenarios (id, group_id, language_id, title, description, level, type, icon, sort_order) VALUES
  (
    '00000000-0000-0000-0005-000000000001',
    '00000000-0000-0000-0000-000000000005',
    'en',
    'Receiving a Package',
    'A courier arrives with a parcel. Practice asking for clarification when you can''t hear clearly, confirming your identity, signing for the delivery, and getting your tracking number.',
    'beginner', 'scripted', '📦', 1
  ),
  (
    '00000000-0000-0000-0005-000000000002',
    '00000000-0000-0000-0000-000000000005',
    'ja',
    '宅配便を受け取る',
    '宅配便が届いた場面を練習します。インターホンで聞き取れない時の聞き返し方、本人確認、サインの方法、お問い合わせ番号の確認まで自然に話せるようにします。',
    'beginner', 'scripted', '📦', 1
  )
ON CONFLICT (id) DO NOTHING;

-- scenario_lines: en — Receiving a Package
DELETE FROM scenario_lines WHERE scenario_id = '00000000-0000-0000-0005-000000000001';
INSERT INTO scenario_lines (scenario_id, language_id, sort_order, speaker, text, translation) VALUES
  ('00000000-0000-0000-0005-000000000001', 'en', 1, 'partner', 'Delivery! I have a package here for a Mister or Miss Nguyen.', 'Giao hàng! Tôi có một bưu kiện cho anh/chị Nguyễn.'),
  ('00000000-0000-0000-0005-000000000001', 'en', 2, 'user', 'Sorry, the intercom is a bit crackly. Could you say that again, please?', 'Xin lỗi, loa bộ đàm hơi tệ. Bạn có thể nói lại được không?'),
  ('00000000-0000-0000-0005-000000000001', 'en', 3, 'partner', 'No problem! I said I have a parcel for Nguyen Minh. I''ll need a signature.', 'Không sao! Tôi nói là tôi có bưu kiện cho Nguyễn Minh. Tôi cần chữ ký.'),
  ('00000000-0000-0000-0005-000000000001', 'en', 4, 'user', 'That''s me! Please come up — third floor, apartment 3B. I''ll buzz you in now.', 'Đó là tôi! Mời lên đây — tầng 3, phòng 3B. Tôi mở cửa cho bạn ngay.'),
  ('00000000-0000-0000-0005-000000000001', 'en', 5, 'partner', 'Here''s your parcel. Could I get you to sign on this screen, please?', 'Đây là bưu kiện của bạn. Nhờ bạn ký trên màn hình này được không?'),
  ('00000000-0000-0000-0005-000000000001', 'en', 6, 'user', 'Of course. Is there anywhere in particular I need to sign?', 'Được thôi. Có chỗ nào cụ thể tôi cần ký không?'),
  ('00000000-0000-0000-0005-000000000001', 'en', 7, 'partner', 'Sign on that line there, and then could you also print your full name underneath?', 'Ký vào dòng đó, rồi bạn có thể viết tay tên đầy đủ bên dưới không?'),
  ('00000000-0000-0000-0005-000000000001', 'en', 8, 'user', 'Sorry, I didn''t catch the second part. Could you repeat that?', 'Xin lỗi, tôi không nghe rõ phần sau. Bạn có thể nhắc lại không?'),
  ('00000000-0000-0000-0005-000000000001', 'en', 9, 'partner', 'Sure! After your signature, just write your name in block letters right below it.', 'Được! Sau chữ ký, chỉ cần viết tên bằng chữ in hoa ngay bên dưới.'),
  ('00000000-0000-0000-0005-000000000001', 'en', 10, 'user', 'Got it. [signs and prints name] Is there anything else I need to do?', 'Hiểu rồi. [ký và viết tên] Còn điều gì tôi cần làm nữa không?'),
  ('00000000-0000-0000-0005-000000000001', 'en', 11, 'partner', 'That''s everything! Your tracking number is Z-X-four-eight-two-nine-one. Have a great day!', 'Xong rồi! Số theo dõi đơn hàng của bạn là ZX-48291. Chúc bạn một ngày tốt lành!'),
  ('00000000-0000-0000-0005-000000000001', 'en', 12, 'user', 'Thank you so much. You too!', 'Cảm ơn bạn rất nhiều. Bạn cũng vậy!');

-- scenario_lines: ja — 宅配便を受け取る
DELETE FROM scenario_lines WHERE scenario_id = '00000000-0000-0000-0005-000000000002';
INSERT INTO scenario_lines (scenario_id, language_id, sort_order, speaker, text, translation, furigana, romaji) VALUES
  ('00000000-0000-0000-0005-000000000002', 'ja', 1, 'partner', 'ヤマト運輸です。グエン・ミン様にお荷物をお届けに参りました。', 'Đây là Yamato Unyu. Tôi đến giao hàng cho anh/chị Nguyen Minh.', 'ヤマトうんゆです。グエン・ミンさまにおにもつをおとどけにまいりました。', 'Yamato Un''yu desu. Guen Min-sama ni o-nimotsu wo o-todoke ni mairimashita.'),
  ('00000000-0000-0000-0005-000000000002', 'ja', 2, 'user', 'すみません、インターホンの音が悪くて聞き取れませんでした。もう一度おっしゃっていただけますか？', 'Xin lỗi, loa bộ đàm không rõ nên tôi không nghe được. Bạn có thể nói lại một lần nữa không?', 'すみません、インターホンのおとがわるくてききとれませんでした。もういちどおっしゃっていただけますか？', 'Sumimasen, intāhon no oto ga warukute kikitoremasen deshita. Mō ichi-do osshatte itadakemasu ka?'),
  ('00000000-0000-0000-0005-000000000002', 'ja', 3, 'partner', 'ヤマト運輸でございます。グエン・ミン様宛のお荷物をお持ちしました。', 'Đây là Yamato Unyu. Tôi mang bưu kiện cho anh/chị Nguyen Minh.', 'ヤマトうんゆでございます。グエン・ミンさまあてのおにもつをおもちしました。', 'Yamato Un''yu de gozaimasu. Guen Min-sama ate no o-nimotsu wo o-mochi shimashita.'),
  ('00000000-0000-0000-0005-000000000002', 'ja', 4, 'user', 'はい、私です。3階の3Bにいます。今、開けますね。', 'Vâng, đó là tôi. Tôi ở tầng 3 phòng 3B. Tôi mở cửa ngay nhé.', 'はい、わたしです。さんがいのさんBにいます。いま、あけますね。', 'Hai, watashi desu. San-kai no san-B ni imasu. Ima, akemasu ne.'),
  ('00000000-0000-0000-0005-000000000002', 'ja', 5, 'partner', 'こちらがお荷物です。こちらの端末にサインをいただけますか？', 'Đây là bưu kiện của bạn. Bạn có thể ký vào màn hình này không?', 'こちらがおにもつです。こちらのたんまつにサインをいただけますか？', 'Kochira ga o-nimotsu desu. Kochira no tanmatsu ni sain wo itadakemasu ka?'),
  ('00000000-0000-0000-0005-000000000002', 'ja', 6, 'user', 'はい。どこにサインすればいいですか？', 'Vâng. Tôi ký vào chỗ nào?', 'はい。どこにサインすればいいですか？', 'Hai. Doko ni sain sureba ii desu ka?'),
  ('00000000-0000-0000-0005-000000000002', 'ja', 7, 'partner', 'この枠内にサインをして、その下にお名前をご記入いただけますか？', 'Ký vào khung này, rồi viết tên vào bên dưới được không?', 'このわくないにサインをして、そのしたにおなまえをごきにゅういただけますか？', 'Kono waku-nai ni sain wo shite, sono shita ni o-namae wo go-kinyū itadakemasu ka?'),
  ('00000000-0000-0000-0005-000000000002', 'ja', 8, 'user', 'すみません、もう一度言っていただけますか？少し聞き取れなかったです。', 'Xin lỗi, bạn có thể nói lại được không? Tôi nghe không rõ lắm.', 'すみません、もういちどいっていただけますか？すこしききとれなかったです。', 'Sumimasen, mō ichi-do itte itadakemasu ka? Sukoshi kikitorenakatta desu.'),
  ('00000000-0000-0000-0005-000000000002', 'ja', 9, 'partner', 'はい、失礼しました。まずサイン欄にサインをして、それからサインの下にお名前をお書きください。', 'Vâng, xin lỗi. Trước tiên ký vào ô chữ ký, rồi viết tên ngay bên dưới chữ ký.', 'はい、しつれいしました。まずサインらんにサインをして、それからサインのしたにおなまえをおかきください。', 'Hai, shitsurei shimashita. Mazu sain-ran ni sain wo shite, sorekara sain no shita ni o-namae wo o-kaki kudasai.'),
  ('00000000-0000-0000-0005-000000000002', 'ja', 10, 'user', 'わかりました。[サイン・記入する] これでよろしいでしょうか？', 'Hiểu rồi. [ký và viết tên] Như vậy có được không?', 'わかりました。[サイン・きにゅうする] これでよろしいでしょうか？', 'Wakarimashita. [sain / kinyū suru] Kore de yoroshii deshō ka?'),
  ('00000000-0000-0000-0005-000000000002', 'ja', 11, 'partner', 'はい、ありがとうございます。お問い合わせ番号はZX-四八二九一でございます。', 'Vâng, cảm ơn bạn. Số theo dõi đơn hàng là ZX-48291.', 'はい、ありがとうございます。おといあわせばんごうはZX-しはちにきゅういちでございます。', 'Hai, arigatō gozaimasu. O-toiawase bangō wa ZX-shi-hachi-ni-kyū-ichi de gozaimasu.'),
  ('00000000-0000-0000-0005-000000000002', 'ja', 12, 'user', 'ありがとうございます。気をつけていってらっしゃいませ。', 'Cảm ơn bạn. Hãy cẩn thận trên đường nhé.', 'ありがとうございます。きをつけていってらっしゃいませ。', 'Arigatō gozaimasu. Ki wo tsukete itterasshai-mase.');
