-- ========================================================================
-- Auto-generated by generate-scenarios-sql.mjs
-- 2026-06-17T00:39:36.606Z
-- ========================================================================

-- ──────────────────────────────────────────────────────────────────────
-- Source : 03_inquire-hours-prices.json
-- Group  : daily-life  (daily)
-- Langs  : en, ja
-- ──────────────────────────────────────────────────────────────────────

-- scenario_groups
INSERT INTO scenario_groups (id, slug, category) VALUES
  ('00000000-0000-0000-0000-000000000006', 'hour-inquiry', 'daily')
ON CONFLICT (id) DO NOTHING;

-- scenarios
INSERT INTO scenarios (id, group_id, language_id, title, description, level, type, icon, sort_order) VALUES
  (
    '00000000-0000-0000-0003-000000000005',
    '00000000-0000-0000-0000-000000000006',
    'en',
    'Calling to Ask About Hours & Admission',
    'Call a museum or attraction to find out opening hours, admission fees, group discounts, and current exhibitions.',
    'beginner', 'scripted', '🏛️', 3
  ),
  (
    '00000000-0000-0000-0003-000000000006',
    '00000000-0000-0000-0000-000000000006',
    'ja',
    '電話で施設の情報を問い合わせる',
    '美術館などの施設に電話して、開館時間・入館料・団体割引・特別展示について問い合わせる練習をします。',
    'beginner', 'scripted', '🏛️', 3
  )
ON CONFLICT (id) DO NOTHING;

-- scenario_lines: en — Calling to Ask About Hours & Admission
DELETE FROM scenario_lines WHERE scenario_id = '00000000-0000-0000-0003-000000000005';
INSERT INTO scenario_lines (scenario_id, language_id, sort_order, speaker, text, translation) VALUES
  ('00000000-0000-0000-0003-000000000005', 'en', 1, 'partner', 'Hello, City Art Museum. How can I help you today?', 'Xin chào, Bảo tàng Nghệ thuật thành phố. Tôi có thể giúp gì cho bạn?'),
  ('00000000-0000-0000-0003-000000000005', 'en', 2, 'user', 'Hi! I''d like to find out your opening hours and admission fees, please.', 'Xin chào! Tôi muốn hỏi về giờ mở cửa và giá vé vào.'),
  ('00000000-0000-0000-0003-000000000005', 'en', 3, 'partner', 'Of course! We''re open Tuesday through Sunday, ten a.m. to six p.m. We''re closed on Mondays.', 'Tất nhiên! Chúng tôi mở cửa từ thứ Ba đến Chủ Nhật, 10h sáng đến 6h chiều. Thứ Hai đóng cửa.'),
  ('00000000-0000-0000-0003-000000000005', 'en', 4, 'user', 'Got it. And how much is admission?', 'Hiểu rồi. Vé vào cửa bao nhiêu tiền?'),
  ('00000000-0000-0000-0003-000000000005', 'en', 5, 'partner', 'Adults are fifteen dollars, students with a valid ID are ten, and children under twelve get in free.', 'Người lớn 15 đô, sinh viên có thẻ 10 đô, trẻ em dưới 12 tuổi miễn phí.'),
  ('00000000-0000-0000-0003-000000000005', 'en', 6, 'user', 'Is there a group discount, by any chance?', 'Có giảm giá cho đoàn không?'),
  ('00000000-0000-0000-0003-000000000005', 'en', 7, 'partner', 'Yes — groups of ten or more get twenty percent off. You''d need to book in advance.', 'Có — đoàn 10 người trở lên được giảm 20%. Cần đặt trước.'),
  ('00000000-0000-0000-0003-000000000005', 'en', 8, 'user', 'Wonderful. Are there any special exhibitions on right now?', 'Tuyệt. Hiện có triển lãm đặc biệt nào không?'),
  ('00000000-0000-0000-0003-000000000005', 'en', 9, 'partner', 'We have a photography exhibition running until the end of the month. It''s included in the regular ticket.', 'Chúng tôi đang có triển lãm nhiếp ảnh đến cuối tháng. Vé vào cửa thường đã bao gồm.'),
  ('00000000-0000-0000-0003-000000000005', 'en', 10, 'user', 'That sounds lovely. Is there parking nearby?', 'Nghe hay đấy. Có bãi đỗ xe gần đó không?'),
  ('00000000-0000-0000-0003-000000000005', 'en', 11, 'partner', 'There''s a public car park right next to us. We validate parking for up to two hours with any paid ticket.', 'Có bãi đỗ xe công cộng ngay bên cạnh. Chúng tôi xác nhận miễn phí đỗ xe tối đa 2 tiếng cho khách có vé.'),
  ('00000000-0000-0000-0003-000000000005', 'en', 12, 'user', 'Perfect, thank you so much for your help. I''ll plan my visit soon!', 'Tuyệt vời, cảm ơn bạn rất nhiều. Tôi sẽ lên kế hoạch đến sớm thôi!');

-- scenario_lines: ja — 電話で施設の情報を問い合わせる
DELETE FROM scenario_lines WHERE scenario_id = '00000000-0000-0000-0003-000000000006';
INSERT INTO scenario_lines (scenario_id, language_id, sort_order, speaker, text, translation, furigana, romaji) VALUES
  ('00000000-0000-0000-0003-000000000006', 'ja', 1, 'partner', 'はい、市立美術館でございます。', 'Vâng, Bảo tàng Nghệ thuật thành phố xin nghe.', 'はい、しりつびじゅつかんでございます。', 'Hai, shiritsu bijutsukan de gozaimasu.'),
  ('00000000-0000-0000-0003-000000000006', 'ja', 2, 'user', 'あの、開館時間と入館料をお教えいただけますか？', 'Xin lỗi, bạn có thể cho tôi biết giờ mở cửa và giá vé không?', 'あの、かいかんじかんとにゅうかんりょうをおしえいただけますか？', 'Ano, kaikan jikan to nyūkan ryō wo oshie itadakemasu ka?'),
  ('00000000-0000-0000-0003-000000000006', 'ja', 3, 'partner', 'かしこまりました。火曜日から日曜日の午前10時から午後6時まで開館しております。月曜日は休館日です。', 'Vâng. Chúng tôi mở cửa từ thứ Ba đến Chủ Nhật, 10h đến 18h. Thứ Hai đóng cửa.', 'かしこまりました。かようびからにちようびのごぜんじゅうじからごごろくじまでかいかんしております。げつようびはきゅうかんびです。', 'Kashikomarimashita. Kayōbi kara nichiyōbi no gozen jū-ji kara gogo roku-ji made kaikan shite orimasu. Getsuyōbi wa kyūkan-bi desu.'),
  ('00000000-0000-0000-0003-000000000006', 'ja', 4, 'user', 'ありがとうございます。入館料はおいくらでしょうか？', 'Cảm ơn. Giá vé vào là bao nhiêu?', 'ありがとうございます。にゅうかんりょうはおいくらでしょうか？', 'Arigatō gozaimasu. Nyūkan ryō wa o-ikura deshō ka?'),
  ('00000000-0000-0000-0003-000000000006', 'ja', 5, 'partner', '大人が1,500円、学生証をお持ちの方は1,000円、12歳以下のお子様は無料でございます。', 'Người lớn 1.500 yên, sinh viên có thẻ 1.000 yên, trẻ em dưới 12 tuổi miễn phí.', 'おとながせんごひゃくえん、がくせいしょうをおもちのかたはせんえん、じゅうにさいいかのおこさまはむりょうでございます。', 'Otona ga sen-go-hyaku-en, gakusei-shō wo o-mochi no kata wa sen-en, jū-ni-sai ika no o-ko-sama wa muryō de gozaimasu.'),
  ('00000000-0000-0000-0003-000000000006', 'ja', 6, 'user', '団体割引はございますか？', 'Có giảm giá cho đoàn không?', 'だんたいわりびきはございますか？', 'Dantai waribiki wa gozaimasu ka?'),
  ('00000000-0000-0000-0003-000000000006', 'ja', 7, 'partner', '10名様以上でご来館の場合、2割引でご利用いただけます。事前のご予約が必要となります。', 'Đoàn từ 10 người trở lên được giảm 20%. Cần đặt trước.', 'じゅうめいさまいじょうでごらいかんのばあい、にわりびきでごりようていただけます。じぜんのごよやくがひつようとなります。', 'Jū-mei-sama ijō de go-raikan no baai, ni-wari-biki de go-riyō itadakemasu. Jizen no go-yoyaku ga hitsuyō to narimasu.'),
  ('00000000-0000-0000-0003-000000000006', 'ja', 8, 'user', 'そうですか。現在、特別な展示はありますか？', 'Vậy à. Hiện có triển lãm đặc biệt nào không?', 'そうですか。げんざい、とくべつなてんじはありますか？', 'Sō desu ka. Genzai, tokubetsu na tenji wa arimasu ka?'),
  ('00000000-0000-0000-0003-000000000006', 'ja', 9, 'partner', 'はい、今月末まで写真展を開催しております。通常の入館料でご覧いただけます。', 'Có, chúng tôi đang tổ chức triển lãm nhiếp ảnh đến cuối tháng. Vé thường đã bao gồm.', 'はい、こんげつまつまでしゃしんてんをかいさいしております。つうじょうのにゅうかんりょうでごらんいただけます。', 'Hai, kongetsu-matsu made shashin-ten wo kaisai shite orimasu. Tsūjō no nyūkan ryō de go-ran itadakemasu.'),
  ('00000000-0000-0000-0003-000000000006', 'ja', 10, 'user', 'それは楽しそうですね。駐車場はございますか？', 'Nghe hay đấy. Có bãi đỗ xe không?', 'それはたのしそうですね。ちゅうしゃじょうはございますか？', 'Sore wa tanoshi-sō desu ne. Chūsha-jō wa gozaimasu ka?'),
  ('00000000-0000-0000-0003-000000000006', 'ja', 11, 'partner', '美術館の隣に公共駐車場がございます。有料入館券をお持ちの方は、2時間分の駐車料を補助いたします。', 'Có bãi đỗ xe công cộng ngay bên cạnh. Khách có vé sẽ được hỗ trợ 2 tiếng phí đỗ xe.', 'びじゅつかんのとなりにこうきょうちゅうしゃじょうがございます。ゆうりょうにゅうかんけんをおもちのかたは、にじかんぶんのちゅうしゃりょうをほじょいたします。', 'Bijutsukan no tonari ni kōkyō chūsha-jō ga gozaimasu. Yūryō nyūkan-ken wo o-mochi no kata wa, ni-jikan bun no chūsha-ryō wo hojo itashimasu.'),
  ('00000000-0000-0000-0003-000000000006', 'ja', 12, 'user', 'わかりました。詳しく教えていただき、ありがとうございました。近いうちに伺います。', 'Hiểu rồi. Cảm ơn bạn đã giải thích chi tiết. Tôi sẽ ghé thăm sớm.', 'わかりました。くわしくおしえていただき、ありがとうございました。ちかいうちにうかがいます。', 'Wakarimashita. Kuwashiku oshiete itadaki, arigatō gozaimashita. Chikai uchi ni ukagaimasu.');
