-- ========================================================================
-- Auto-generated by generate-scenarios-sql.mjs
-- 2026-06-16T15:58:05.342Z
-- ========================================================================

-- ──────────────────────────────────────────────────────────────────────
-- Source : 02_taxi-grab-call.json
-- Group  : daily-life  (daily)
-- Langs  : en, ja
-- ──────────────────────────────────────────────────────────────────────

-- scenario_groups
INSERT INTO scenario_groups (id, slug, category) VALUES
  ('00000000-0000-0000-0000-000000000004', 'taxi', 'taxi')
ON CONFLICT (id) DO NOTHING;

-- scenarios
INSERT INTO scenarios (id, group_id, language_id, title, description, level, type, icon, sort_order) VALUES
  (
    '00000000-0000-0000-0003-000000000003',
    '00000000-0000-0000-0000-000000000004',
    'en',
    'Calling a Taxi / Ride',
    'Call a taxi dispatcher, give your pickup address and destination, and pass on special instructions — don''t use the back gate, waiting under the building, in a hurry for a flight.',
    'intermediate', 'scripted', '🚕', 2
  ),
  (
    '00000000-0000-0000-0003-000000000004',
    '00000000-0000-0000-0000-000000000004',
    'ja',
    '電話でタクシーを呼ぶ',
    'タクシー会社に電話して、乗車場所・目的地を伝え、裏口不可・建物前で待機などの特別な要望も練習します。',
    'intermediate', 'scripted', '🚕', 2
  )
ON CONFLICT (id) DO NOTHING;

-- scenario_lines: en — Calling a Taxi / Ride
DELETE FROM scenario_lines WHERE scenario_id = '00000000-0000-0000-0003-000000000003';
INSERT INTO scenario_lines (scenario_id, language_id, sort_order, speaker, text, translation) VALUES
  ('00000000-0000-0000-0003-000000000003', 'en', 1, 'partner', 'City Cab, how can I help you?', 'Taxi City Cab đây, tôi có thể giúp gì cho bạn?'),
  ('00000000-0000-0000-0003-000000000003', 'en', 2, 'user', 'Hi, I''d like to book a taxi, please. I need one as soon as possible.', 'Xin chào, tôi muốn đặt taxi, nhanh nhất có thể.'),
  ('00000000-0000-0000-0003-000000000003', 'en', 3, 'partner', 'Sure! Where are you being picked up from?', 'Được! Bạn đang ở địa chỉ đón nào?'),
  ('00000000-0000-0000-0003-000000000003', 'en', 4, 'user', 'I''m at 123 Nguyen Hue Street, District 1. I''m waiting under the building, at the ground-floor drop-off area.', 'Tôi đang ở 123 Nguyễn Huệ, Quận 1. Tôi đang đứng dưới tòa nhà, khu vực đón xe tầng trệt.'),
  ('00000000-0000-0000-0003-000000000003', 'en', 5, 'partner', 'Got it. And where are you heading?', 'Hiểu rồi. Bạn muốn đến đâu?'),
  ('00000000-0000-0000-0003-000000000003', 'en', 6, 'user', 'To Tan Son Nhat Airport, please. I have a flight at two-thirty, so I''m in a bit of a rush.', 'Đến sân bay Tân Sơn Nhất. Tôi có chuyến bay lúc 2 rưỡi nên hơi vội.'),
  ('00000000-0000-0000-0003-000000000003', 'en', 7, 'partner', 'No problem. Any special instructions for the driver?', 'Không vấn đề. Có yêu cầu gì đặc biệt cho tài xế không?'),
  ('00000000-0000-0000-0003-000000000003', 'en', 8, 'user', 'Yes — please tell the driver not to come through the back gate, it''s locked. The main entrance is on Nguyen Hue Street.', 'Có — nhờ bạn nhắn tài xế đừng vào cổng sau, cổng đó bị khóa. Lối vào chính ở phía đường Nguyễn Huệ.'),
  ('00000000-0000-0000-0003-000000000003', 'en', 9, 'partner', 'Understood. I''ll pass that on. May I have your name?', 'Hiểu rồi. Tôi sẽ thông báo cho tài xế. Cho tôi xin tên bạn?'),
  ('00000000-0000-0000-0003-000000000003', 'en', 10, 'user', 'It''s Minh. And my number is zero-nine-zero, one-two-three-four, five-six-seven-eight.', 'Tên tôi là Minh. Số điện thoại là 090-1234-5678.'),
  ('00000000-0000-0000-0003-000000000003', 'en', 11, 'partner', 'Thank you, Minh. Your driver will arrive in about eight minutes. It''s a white Toyota Vios, license plate fifty-one A, one-two-three-four.', 'Cảm ơn anh/chị Minh. Tài xế sẽ đến trong khoảng 8 phút. Xe Toyota Vios trắng, biển số 51A-1234.'),
  ('00000000-0000-0000-0003-000000000003', 'en', 12, 'user', 'Perfect, thank you. I''ll keep an eye out for it.', 'Tuyệt, cảm ơn. Tôi sẽ chú ý.');

-- scenario_lines: ja — 電話でタクシーを呼ぶ
DELETE FROM scenario_lines WHERE scenario_id = '00000000-0000-0000-0003-000000000004';
INSERT INTO scenario_lines (scenario_id, language_id, sort_order, speaker, text, translation, furigana, romaji) VALUES
  ('00000000-0000-0000-0003-000000000004', 'ja', 1, 'partner', 'はい、シティタクシーでございます。', 'Vâng, đây là City Taxi.', 'はい、シティタクシーでございます。', 'Hai, Shiti-Takushī de gozaimasu.'),
  ('00000000-0000-0000-0003-000000000004', 'ja', 2, 'user', 'すみません、タクシーをお願いしたいのですが、できるだけ早く来ていただけますか？', 'Xin lỗi, tôi muốn đặt taxi, có thể đến sớm nhất không?', 'すみません、タクシーをおねがいしたいのですが、できるだけはやくきていただけますか？', 'Sumimasen, takushī wo onegai shitai no desu ga, dekiru dake hayaku kite itadakemasu ka?'),
  ('00000000-0000-0000-0003-000000000004', 'ja', 3, 'partner', 'かしこまりました。ご乗車場所をお知らせいただけますか？', 'Vâng. Xin cho biết địa điểm đón?', 'かしこまりました。ごじょうしゃばしょをおしらせいただけますか？', 'Kashikomarimashita. Go-jōsha-basho wo o-shirase itadakemasu ka?'),
  ('00000000-0000-0000-0003-000000000004', 'ja', 4, 'user', '渋谷区神南一丁目、ABCタワーの前です。建物の一階、車寄せの下で待っています。', 'Số 1 Jinnan, Shibuya, trước tòa nhà ABC Tower. Tôi đang đứng dưới mái che khu đón xe tầng 1.', 'しぶやくじんなんいちちょうめ、ABCタワーのまえです。たてもののいっかい、くるまよせのしたでまっています。', 'Shibuya-ku Jinnan ichi-chōme, ABC Tawā no mae desu. Tatemono no ikkai, kurumayose no shita de matte imasu.'),
  ('00000000-0000-0000-0003-000000000004', 'ja', 5, 'partner', 'ありがとうございます。行き先はどちらでしょうか？', 'Cảm ơn. Bạn muốn đến đâu?', 'ありがとうございます。いきさきはどちらでしょうか？', 'Arigatō gozaimasu. Ikisaki wa dochira deshō ka?'),
  ('00000000-0000-0000-0003-000000000004', 'ja', 6, 'user', '羽田空港までお願いします。14時のフライトなので、少し急いでいます。', 'Đến sân bay Haneda. Tôi có chuyến bay lúc 14 giờ nên hơi vội.', 'はねだくうこうまでおねがいします。じゅうよじのフライトなので、すこしいそいでいます。', 'Haneda Kūkō made onegai shimasu. Jū-yo-ji no furaito nanode, sukoshi isoide imasu.'),
  ('00000000-0000-0000-0003-000000000004', 'ja', 7, 'partner', 'かしこまりました。何かご要望はございますか？', 'Vâng. Bạn có yêu cầu gì đặc biệt không?', 'かしこまりました。なにかごようぼうはございますか？', 'Kashikomarimashita. Nanika go-yōbō wa gozaimasu ka?'),
  ('00000000-0000-0000-0003-000000000004', 'ja', 8, 'user', 'はい、裏口からは入らないでください。正面玄関はABCタワーの神南通り側にあります。', 'Vâng, xin đừng vào cổng sau. Lối vào chính của tòa ABC Tower nằm ở phía đường Jinnan.', 'はい、うらぐちからははいらないでください。しょうめんげんかんはABCタワーのじんなんどおりがわにあります。', 'Hai, uraguchi kara wa hairanaide kudasai. Shōmen-genkan wa ABC Tawā no Jinnan-dōri gawa ni arimasu.'),
  ('00000000-0000-0000-0003-000000000004', 'ja', 9, 'partner', '承知いたしました。お名前とご連絡先をお聞かせいただけますか？', 'Vâng, tôi hiểu. Cho tôi xin tên và số điện thoại liên lạc?', 'しょうちいたしました。おなまえとごれんらくさきをおきかせいただけますか？', 'Shōchi itashimashita. O-namae to go-renrakusaki wo o-kikase itadakemasu ka?'),
  ('00000000-0000-0000-0003-000000000004', 'ja', 10, 'user', 'グエン・ミンと申します。電話番号は○九○の一二三四の五六七八です。', 'Tôi là Nguyen Minh. Số điện thoại là 090-1234-5678.', 'グエン・ミンともうします。でんわばんごうはまるきゅうまるのいちにさんしのごろくしちはちです。', 'Guen Min to mōshimasu. Denwa-bangō wa maru-kyū-maru no ichi-ni-san-shi no go-roku-shichi-hachi desu.'),
  ('00000000-0000-0000-0003-000000000004', 'ja', 11, 'partner', 'ありがとうございます。10分ほどでお迎えに参ります。白いプリウスで、ナンバーは品川500あ1234でございます。', 'Cảm ơn. Tài xế sẽ đến trong khoảng 10 phút. Xe Prius màu trắng, biển số Shinagawa 500-A-1234.', 'ありがとうございます。じゅっぷんほどでおむかえにまいります。しろいプリウスで、ナンバーはしながわごひゃくあいちにさんよんでございます。', 'Arigatō gozaimasu. Juppun hodo de o-mukae ni mairimasu. Shiroi Priusu de, nanbā wa Shinagawa go-hyaku a ichi-ni-san-yon de gozaimasu.'),
  ('00000000-0000-0000-0003-000000000004', 'ja', 12, 'user', 'わかりました。ありがとうございます。よろしくお願いします。', 'Hiểu rồi. Cảm ơn bạn. Nhờ bạn nhé.', 'わかりました。ありがとうございます。よろしくおねがいします。', 'Wakarimashita. Arigatō gozaimasu. Yoroshiku onegai shimasu.');
