-- Auto-generated SQL for 66 missions

insert into stickers (id, name, theme, emoji, sort_order) values
  ('sticker-103', 'Mèo tinh nghịch', 'rewards', '🐱', 103),
  ('sticker-104', 'Cún Golden', 'rewards', '🦮', 104),
  ('sticker-105', 'Poodle đáng yêu', 'rewards', '🐩', 105),
  ('sticker-106', 'Dâu tây đỏ', 'rewards', '🍓', 106),
  ('sticker-107', 'Chuối chín vàng', 'rewards', '🍌', 107),
  ('sticker-108', 'Bát salad tươi', 'rewards', '🥗', 108),
  ('sticker-109', 'Áo choàng đỏ', 'rewards', '🦸', 109),
  ('sticker-110', 'Khiên công lý', 'rewards', '🛡', 110),
  ('sticker-111', 'Tia chớp vàng', 'rewards', '⚡', 111),
  ('sticker-112', 'Chiếc chổi nhỏ', 'rewards', '🧹', 112),
  ('sticker-113', 'Hộp đồ chơi', 'rewards', '📦', 113),
  ('sticker-114', 'Giường ngăn nắp', 'rewards', '🛏', 114),
  ('sticker-115', 'Đám mây mưa', 'rewards', '🌧', 115),
  ('sticker-116', 'Áo mưa vàng', 'rewards', '🧥', 116),
  ('sticker-117', 'Chiếc ô nhỏ', 'rewards', '🌂', 117),
  ('sticker-118', 'Xích đu nhỏ', 'rewards', '🎠', 118),
  ('sticker-119', 'Diều bay cao', 'rewards', '🪁', 119),
  ('sticker-120', 'Quả bóng bay', 'rewards', '🎈', 120),
  ('sticker-121', 'Tivi màn hình', 'rewards', '📺', 121),
  ('sticker-122', 'Bắp rang bơ', 'rewards', '🍿', 122),
  ('sticker-123', 'Tay cầm game', 'rewards', '🕹', 123),
  ('sticker-124', 'Kính bơi xanh', 'rewards', '🏊', 124),
  ('sticker-125', 'Phao cứu hộ', 'rewards', '🛟', 125),
  ('sticker-126', 'Đồ bơi nhỏ', 'rewards', '🩱', 126),
  ('sticker-127', 'Kéo thủ công', 'rewards', '✂', 127),
  ('sticker-128', 'Lọ hồ dán', 'rewards', '🧪', 128),
  ('sticker-129', 'Máy bay giấy', 'rewards', '✈', 129),
  ('sticker-130', 'Bàn chải xinh', 'rewards', '🪥', 130),
  ('sticker-131', 'Kem vị dâu', 'rewards', '🧴', 131),
  ('sticker-132', 'Xe siêu thị', 'rewards', '🛒', 132),
  ('sticker-133', 'Bút chì màu', 'rewards', '✏', 133),
  ('sticker-134', 'Gọt chì đỏ', 'rewards', '🪒', 134),
  ('sticker-135', 'Khay màu vẽ', 'rewards', '🎨', 135),
  ('sticker-136', 'Điểm mười tròn', 'rewards', '💯', 136),
  ('sticker-137', 'Bài thi A+', 'rewards', '📝', 137),
  ('sticker-138', 'Ngôi sao đỏ', 'rewards', '🌟', 138),
  ('sticker-139', 'Mầm cây non', 'rewards', '🌱', 139),
  ('sticker-140', 'Xẻng nhỏ vườn', 'rewards', '🧑‍🌾', 140),
  ('sticker-141', 'Bình tưới cây', 'rewards', '🚿', 141),
  ('sticker-142', 'Răng khỏe mạnh', 'rewards', '🦷', 142),
  ('sticker-143', 'Bàn chải sạch', 'rewards', '🪥', 143),
  ('sticker-144', 'Quả táo ngọt', 'rewards', '🍎', 144),
  ('sticker-145', 'Điện thoại bàn', 'rewards', '☎', 145),
  ('sticker-146', 'Bà ngoại hiền', 'rewards', '👵', 146),
  ('sticker-147', 'Ông ngoại hiền', 'rewards', '👴', 147),
  ('sticker-148', 'Giỏ dã ngoại', 'rewards', '🧺', 148),
  ('sticker-149', 'Bánh sandwich ngon', 'rewards', '🥪', 149),
  ('sticker-150', 'Cây rợp bóng', 'rewards', '🌳', 150),
  ('sticker-151', 'Máy kéo đỏ', 'rewards', '🚜', 151),
  ('sticker-152', 'Gà con vàng', 'rewards', '🐥', 152),
  ('sticker-153', 'Nhánh lúa chín', 'rewards', '🌾', 153),
  ('sticker-154', 'Lều ấm cúng', 'rewards', '⛺', 154),
  ('sticker-155', 'Đống củi khô', 'rewards', '🪵', 155),
  ('sticker-156', 'Kẹo dẻo nướng', 'rewards', '🍢', 156),
  ('sticker-157', 'Chú khỉ trốn', 'rewards', '🙈', 157),
  ('sticker-158', 'Cánh cửa gỗ', 'rewards', '🚪', 158),
  ('sticker-159', 'Kính lúp tìm', 'rewards', '🕵', 159),
  ('sticker-160', 'Gấu bông nhỏ', 'rewards', '🧸', 160),
  ('sticker-161', 'Mảnh ghép lego', 'rewards', '🧩', 161),
  ('sticker-162', 'Rổ đồ chơi', 'rewards', '🧺', 162),
  ('sticker-163', 'Xe đạp nhỏ', 'rewards', '🚲', 163),
  ('sticker-164', 'Mũ bảo hiểm', 'rewards', '🪖', 164),
  ('sticker-165', 'Vạch đích đỏ', 'rewards', '🏁', 165),
  ('sticker-166', 'Bà cụ hiền', 'rewards', '👵', 166),
  ('sticker-167', 'Đèn giao thông', 'rewards', '🚦', 167),
  ('sticker-168', 'Biển báo hiệu', 'rewards', '🚸', 168),
  ('sticker-169', 'Bánh mì gối', 'rewards', '🍞', 169),
  ('sticker-170', 'Phô mai béo', 'rewards', '🧀', 170),
  ('sticker-171', 'Thịt nguội ngon', 'rewards', '🥓', 171),
  ('sticker-172', 'Đám mây mơ', 'rewards', '😴', 172),
  ('sticker-173', 'Voi hồng bay', 'rewards', '🐘', 173),
  ('sticker-174', 'Ly kem lớn', 'rewards', '🍦', 174),
  ('sticker-175', 'Quân tốt gỗ', 'rewards', '♟', 175),
  ('sticker-176', 'Quân mã đẹp', 'rewards', '🐴', 176),
  ('sticker-177', 'Vương miện vàng', 'rewards', '👑', 177),
  ('sticker-178', 'Chiếc cốc vỡ', 'rewards', '🥛', 178),
  ('sticker-179', 'Chổi dọn dẹp', 'rewards', '🧹', 179),
  ('sticker-180', 'Mặt hối lỗi', 'rewards', '🥺', 180),
  ('sticker-181', 'Đồng hồ tay', 'rewards', '⌚', 181),
  ('sticker-182', 'Đồng hồ bàn', 'rewards', '⏰', 182),
  ('sticker-183', 'Xe buýt học', 'rewards', '🚌', 183),
  ('sticker-184', 'Bảng pha màu', 'rewards', '🎨', 184),
  ('sticker-185', 'Khủng long con', 'rewards', '🦕', 185),
  ('sticker-186', 'Khung tranh nhỏ', 'rewards', '🖼', 186),
  ('sticker-187', 'Quả bóng tròn', 'rewards', '⚽', 187),
  ('sticker-188', 'Khung thành rộng', 'rewards', '🥅', 188),
  ('sticker-189', 'Cúp vàng nhỏ', 'rewards', '🏆', 189),
  ('sticker-190', 'Ngôi nhà nhỏ', 'rewards', '🏠', 190),
  ('sticker-191', 'Bánh quy ngon', 'rewards', '🍪', 191),
  ('sticker-192', 'Hộp đồ chơi', 'rewards', '🧩', 192),
  ('sticker-193', 'Diều giấy màu', 'rewards', '🪁', 193),
  ('sticker-194', 'Cơn gió mát', 'rewards', '💨', 194),
  ('sticker-195', 'Cánh đồng cỏ', 'rewards', '🌾', 195),
  ('sticker-196', 'Lâu đài cát', 'rewards', '🏖', 196),
  ('sticker-197', 'Xô nhựa nhỏ', 'rewards', '🪣', 197),
  ('sticker-198', 'Vỏ sò nhỏ', 'rewards', '🐚', 198),
  ('sticker-199', 'Khủng long bạo', 'rewards', '🦖', 199),
  ('sticker-200', 'Bộ xương cổ', 'rewards', '🦴', 200),
  ('sticker-201', 'Máy ảnh nhỏ', 'rewards', '📷', 201),
  ('sticker-202', 'Hộp bưu kiện', 'rewards', '📦', 202),
  ('sticker-203', 'Xe giao hàng', 'rewards', '🚚', 203),
  ('sticker-204', 'Phiếu ký nhận', 'rewards', '📋', 204),
  ('sticker-205', 'Tấm thiệp xinh', 'rewards', '💌', 205),
  ('sticker-206', 'Trái tim đỏ', 'rewards', '💖', 206),
  ('sticker-207', 'Bút sáp hồng', 'rewards', '🖍', 207),
  ('sticker-208', 'Kính viễn vọng', 'rewards', '🔭', 208),
  ('sticker-209', 'Trăng khuyết sáng', 'rewards', '🌙', 209),
  ('sticker-210', 'Ngôi sao đêm', 'rewards', '🌟', 210),
  ('sticker-211', 'Người tuyết nhỏ', 'rewards', '⛄', 211),
  ('sticker-212', 'Củ cà rốt', 'rewards', '🥕', 212),
  ('sticker-213', 'Khăn len đỏ', 'rewards', '🧣', 213),
  ('sticker-214', 'Đường tàu lượn', 'rewards', '🎢', 214),
  ('sticker-215', 'Vé công viên', 'rewards', '🎫', 215),
  ('sticker-216', 'Mặt ngạc nhiên', 'rewards', '🙀', 216),
  ('sticker-217', 'Hộp quà xinh', 'rewards', '🎁', 217),
  ('sticker-218', 'Chiếc nơ xinh', 'rewards', '🎀', 218),
  ('sticker-219', 'Băng keo nhỏ', 'rewards', '✂', 219),
  ('sticker-220', 'Quả táo đỏ', 'rewards', '🍎', 220),
  ('sticker-221', 'Giỏ hái táo', 'rewards', '🧺', 221),
  ('sticker-222', 'Bánh táo nướng', 'rewards', '🥧', 222),
  ('sticker-223', 'Cây thông nhỏ', 'rewards', '🎄', 223),
  ('sticker-224', 'Ngôi sao vàng', 'rewards', '🌟', 224),
  ('sticker-225', 'Quả chuông nhỏ', 'rewards', '🔔', 225),
  ('sticker-226', 'Hoa hướng dương', 'rewards', '🌻', 226),
  ('sticker-227', 'Bó hoa hồng', 'rewards', '💐', 227),
  ('sticker-228', 'Nơ thắt xinh', 'rewards', '🎀', 228),
  ('sticker-229', 'Võ phục trắng', 'rewards', '🥋', 229),
  ('sticker-230', 'Nắm đấm nhỏ', 'rewards', '🤜', 230),
  ('sticker-231', 'Tấm gỗ tập', 'rewards', '🪵', 231),
  ('sticker-232', 'Cá hề xinh', 'rewards', '🐠', 232),
  ('sticker-233', 'Cá mập to', 'rewards', '🦈', 233),
  ('sticker-234', 'Rùa biển nhỏ', 'rewards', '🐢', 234),
  ('sticker-235', 'Rạp xiếc lớn', 'rewards', '🎪', 235),
  ('sticker-236', 'Chú hề vui', 'rewards', '🤡', 236),
  ('sticker-237', 'Sư tử xiếc', 'rewards', '🦁', 237),
  ('sticker-238', 'Xe hơi sạch', 'rewards', '🚗', 238),
  ('sticker-239', 'Bọt biển mềm', 'rewards', '🧽', 239),
  ('sticker-240', 'Bọt xà phòng', 'rewards', '🫧', 240),
  ('sticker-241', 'Bánh quy bơ', 'rewards', '🍪', 241),
  ('sticker-242', 'Trục cán bột', 'rewards', '🥖', 242),
  ('sticker-243', 'Ly sữa ấm', 'rewards', '🥛', 243),
  ('sticker-244', 'Con ma nhỏ', 'rewards', '👻', 244),
  ('sticker-245', 'Mũ hải tặc', 'rewards', '🏴‍☠️', 245),
  ('sticker-246', 'Kẹo ngọt nhỏ', 'rewards', '🍬', 246),
  ('sticker-247', 'Giày trượt đỏ', 'rewards', '🛼', 247),
  ('sticker-248', 'Băng cá nhân', 'rewards', '🩹', 248),
  ('sticker-249', 'Ngón tay tốt', 'rewards', '👍', 249),
  ('sticker-250', 'Bướm nhỏ xinh', 'rewards', '🦋', 250),
  ('sticker-251', 'Vợt bắt bướm', 'rewards', '🕸', 251),
  ('sticker-252', 'Bông hoa nở', 'rewards', '🌸', 252),
  ('sticker-253', 'Cuốn truyện nhỏ', 'rewards', '📚', 253),
  ('sticker-254', 'Đóng xu nhỏ', 'rewards', '🪙', 254),
  ('sticker-255', 'Thẻ kẹp sách', 'rewards', '🔖', 255),
  ('sticker-256', 'Cần câu tre', 'rewards', '🎣', 256),
  ('sticker-257', 'Con mồi nhỏ', 'rewards', '🐛', 257),
  ('sticker-258', 'Chú cá nhỏ', 'rewards', '🐟', 258),
  ('sticker-259', 'Thuyền giấy đỏ', 'rewards', '⛵', 259),
  ('sticker-260', 'Chiếc ô nhỏ', 'rewards', '☔', 260),
  ('sticker-261', 'Vũng nước nhỏ', 'rewards', '🌊', 261),
  ('sticker-262', 'Cầu vồng xinh', 'rewards', '🌈', 262),
  ('sticker-263', 'Bút vẽ màu', 'rewards', '🖍', 263),
  ('sticker-264', 'Huy chương vàng', 'rewards', '🏆', 264),
  ('sticker-265', 'Lều chăn nhỏ', 'rewards', '⛺', 265),
  ('sticker-266', 'Ghế sofa lớn', 'rewards', '🛋', 266),
  ('sticker-267', 'Đèn pin nhỏ', 'rewards', '🔦', 267),
  ('sticker-268', 'Lồng đèn sao', 'rewards', '🏮', 268),
  ('sticker-269', 'Cành tre nhỏ', 'rewards', '🎋', 269),
  ('sticker-270', 'Cây nến nhỏ', 'rewards', '🕯', 270),
  ('sticker-271', 'Đầu lân đỏ', 'rewards', '🦁', 271),
  ('sticker-272', 'Tiếng trống hội', 'rewards', '🥁', 272),
  ('sticker-273', 'Cây bắp cải', 'rewards', '🥬', 273),
  ('sticker-274', 'Chú bảo vệ', 'rewards', '🕵', 274),
  ('sticker-275', 'Áo xanh mẹ', 'rewards', '👕', 275),
  ('sticker-276', 'Chiếc loa nhỏ', 'rewards', '📢', 276),
  ('sticker-277', 'Máy bay lớn', 'rewards', '✈', 277),
  ('sticker-278', 'Cuốn hộ chiếu', 'rewards', '🛂', 278),
  ('sticker-279', 'Cửa sổ nhỏ', 'rewards', '🪟', 279),
  ('sticker-280', 'Cún lấm bùn', 'rewards', '🐶', 280),
  ('sticker-281', 'Bồn nước ấm', 'rewards', '🛁', 281),
  ('sticker-282', 'Chai sữa tắm', 'rewards', '🧴', 282),
  ('sticker-283', 'Kính cận xanh', 'rewards', '👓', 283),
  ('sticker-284', 'Bác sĩ mắt', 'rewards', '🩺', 284),
  ('sticker-285', 'Bảng chữ đo', 'rewards', '👁', 285),
  ('sticker-286', 'Tượng Pikachu', 'rewards', '🖌', 286),
  ('sticker-287', 'Khay pha màu', 'rewards', '🎨', 287),
  ('sticker-288', 'Má đỏ tượng', 'rewards', '⚡', 288),
  ('sticker-289', 'Xe cứu hỏa', 'rewards', '🚒', 289),
  ('sticker-290', 'Mũ bảo hộ', 'rewards', '🪖', 290),
  ('sticker-291', 'Còi báo động', 'rewards', '🚨', 291),
  ('sticker-292', 'Rồng múa nước', 'rewards', '🐉', 292),
  ('sticker-293', 'Con rối gỗ', 'rewards', '🎭', 293),
  ('sticker-294', 'Trống truyền thống', 'rewards', '🥁', 294),
  ('sticker-295', 'Ván trượt tuyết', 'rewards', '🛷', 295),
  ('sticker-296', 'Đồi tuyết trắng', 'rewards', '🏔', 296),
  ('sticker-297', 'Bông tuyết nhỏ', 'rewards', '❄', 297),
  ('sticker-298', 'Heo đất hồng', 'rewards', '🐷', 298),
  ('sticker-299', 'Đồng tiền nhỏ', 'rewards', '🪙', 299),
  ('sticker-300', 'Chiếc xe đạp', 'rewards', '🚲', 300)
on conflict (id) do update set
  name = excluded.name,
  emoji = excluded.emoji;

do $$
declare
  m record;
  v_mission_id uuid;
begin
  for m in (
    select * from (values
      ('Nhận nuôi thú cưng', 'adopting a pet at the shelter', '🐶',
        array['sticker-103', 'sticker-104', 'sticker-105'],
        'Hello!', 'Trẻ chào nhân viên trạm cứu hộ thú cưng.',
        'Can I adopt a kitten, please?', 'Trẻ hỏi xin nhận nuôi một bé mèo con (kitten / puppy).',
        'The black and white one, please.', 'Trẻ chọn màu sắc của thú cưng (black and white / yellow / grey).',
        'I will feed her every day.', 'Trẻ hứa sẽ chăm sóc thú cưng chu đáo (feed her every day / play with her).',
        'Thank you! Goodbye!', 'Trẻ cảm ơn nhân viên và chào tạm biệt.'),
      ('Làm món sa-lát trái cây', 'making a fruit salad', '🥗',
        array['sticker-106', 'sticker-107', 'sticker-108'],
        'Good morning!', 'Trẻ chào bạn cùng làm bếp.',
        'Let''s wash the strawberries first.', 'Trẻ đề nghị rửa loại trái cây đầu tiên (strawberries / grapes / apples).',
        'Can you cut the bananas, please?', 'Trẻ nhờ bạn cắt loại trái cây thứ hai (bananas / mangoes).',
        'Let''s mix them in the big bowl.', 'Trẻ rủ bạn trộn tất cả trái cây vào bát lớn.',
        'It looks delicious! Thank you!', 'Trẻ khen món ăn ngon mắt và cảm ơn bạn.'),
      ('Kể về siêu anh hùng', 'describing a superhero', '🦸',
        array['sticker-109', 'sticker-110', 'sticker-111'],
        'Look at this!', 'Trẻ chỉ cho bạn xem hình/tượng siêu anh hùng.',
        'My favorite superhero is Spiderman.', 'Trẻ giới thiệu siêu anh hùng yêu thích của mình (Spiderman / Batman / Iron Man).',
        'He wears a red and blue suit.', 'Trẻ mô tả màu sắc bộ trang phục (red and blue / black / gold).',
        'He can climb tall buildings.', 'Trẻ kể về siêu năng lực đặc biệt (climb buildings / fly / run fast).',
        'He is very cool!', 'Trẻ khen ngợi siêu anh hùng thật ngầu để kết thúc.'),
      ('Dọn dẹp phòng ngủ', 'cleaning my bedroom', '🧹',
        array['sticker-112', 'sticker-113', 'sticker-114'],
        'Let''s clean my bedroom!', 'Trẻ rủ nhân vật đồng hành/bạn dọn dẹp phòng ngủ.',
        'I will put the toys in the box.', 'Trẻ dọn dẹp đồ chơi và cất chúng vào hộp.',
        'Can you help me make the bed, please?', 'Trẻ nhờ giúp dọn dẹp giường ngủ ngăn nắp.',
        'I will wipe the desk.', 'Trẻ lau dọn bàn học gọn gàng.',
        'Wow, my room looks so clean!', 'Trẻ tự hào ngắm nhìn căn phòng sạch sẽ và hoàn thành.'),
      ('Chuẩn bị đi học ngày mưa', 'preparing for a rainy school day', '🌧️',
        array['sticker-115', 'sticker-116', 'sticker-117'],
        'Look outside, it is raining!', 'Trẻ chỉ ra ngoài cửa sổ báo trời đang mưa.',
        'I need to wear my yellow raincoat.', 'Trẻ nói cần mặc áo mưa (yellow / red / blue raincoat).',
        'Can you hand me my boots, please?', 'Trẻ nhờ lấy đôi ủng đi mưa.',
        'I will carry my umbrella too.', 'Trẻ nói sẽ mang theo chiếc ô để che chắn.',
        'I am ready for school. Let''s go!', 'Trẻ sẵn sàng đi học và rủ bố mẹ khởi hành.'),
      ('Chơi xích đu ở sân chơi', 'playing on the swings', '🎠',
        array['sticker-118', 'sticker-119', 'sticker-120'],
        'Hi, can I play on the swings?', 'Trẻ chào bạn ở sân chơi và xin phép chơi xích đu.',
        'Can you push me, please?', 'Trẻ nhờ bạn đẩy hộ xích đu.',
        'Higher, please!', 'Trẻ thích thú muốn đẩy cao hơn chút nữa.',
        'It is so fun!', 'Trẻ bày tỏ niềm vui khi đang bay lượn trên xích đu.',
        'Thank you! It is your turn now.', 'Trẻ cảm ơn bạn và nhường lượt chơi tiếp theo.'),
      ('Xin phép xem TV', 'asking permission to watch TV', '📺',
        array['sticker-121', 'sticker-122', 'sticker-123'],
        'Mom, can I watch TV, please?', 'Trẻ xin phép mẹ/bố xem TV.',
        'I finished all my homework.', 'Trẻ trình bày lý do đã làm xong bài tập về nhà.',
        'I want to watch cartoons.', 'Trẻ nói chương trình muốn xem (cartoons / animal shows).',
        'Just for thirty minutes, please.', 'Trẻ thương lượng thời gian xem (thirty minutes / one hour).',
        'Thank you, Mom! You are the best!', 'Trẻ cảm ơn mẹ vui vẻ.'),
      ('Đi bơi ở hồ bơi', 'going swimming at the pool', '🏊',
        array['sticker-124', 'sticker-125', 'sticker-126'],
        'Hello! One child ticket, please.', 'Trẻ mua vé vào cổng hồ bơi.',
        'Where is the locker room, please?', 'Trẻ hỏi đường đến phòng thay đồ.',
        'I have my swimsuit and goggles.', 'Trẻ kể đồ dùng đã mang theo (swimsuit / goggles / towel).',
        'Can I jump into the water now?', 'Trẻ xin phép nhảy xuống nước bơi.',
        'The water is so cool! Thank you!', 'Trẻ bày tỏ sự thích thú khi bơi.'),
      ('Nhờ giúp làm bài tập thủ công', 'asking for help with an art project', '✂️',
        array['sticker-127', 'sticker-128', 'sticker-129'],
        'Dad, can you help me, please?', 'Trẻ nhờ bố/mẹ giúp đỡ làm bài tập.',
        'I need to make a paper plane.', 'Trẻ nói món đồ cần làm (paper plane / paper boat).',
        'Where is the glue and scissors?', 'Trẻ hỏi tìm dụng cụ (glue / scissors / color pens).',
        'Look! It can fly very far.', 'Trẻ khoe thành quả bay xa (fly very far / look very nice).',
        'Thank you for helping me, Dad!', 'Trẻ cảm ơn bố đã giúp.'),
      ('Mua kem đánh răng', 'buying toothpaste at the supermarket', '🛒',
        array['sticker-130', 'sticker-131', 'sticker-132'],
        'Excuse me, where is the toothpaste?', 'Trẻ hỏi nhân viên vị trí quầy kem đánh răng.',
        'I want strawberry flavor, please.', 'Trẻ nói vị kem muốn mua (strawberry / mint).',
        'Can I have a blue toothbrush too?', 'Trẻ xin mua thêm một chiếc bàn chải màu xanh.',
        'Here is the money.', 'Trẻ thanh toán tiền tại quầy.',
        'Thank you! Have a good day!', 'Trẻ cảm ơn và chúc nhân viên ngày mới tốt lành.'),
      ('Mượn gọt bút chì', 'borrowing a pencil sharpener', '✏️',
        array['sticker-133', 'sticker-134', 'sticker-135'],
        'Hi, my pencil is broken.', 'Trẻ thông báo bút chì bị gãy ngòi.',
        'Can I borrow your sharpener, please?', 'Trẻ mượn cái gọt bút chì của bạn.',
        'Is it the red one?', 'Trẻ hỏi xác nhận màu sắc đồ vật (red one / blue one).',
        'Here you go. Thank you!', 'Trẻ trả lại đồ và cảm ơn bạn.',
        'Now I can draw my picture.', 'Trẻ khoe có thể tiếp tục vẽ tranh.'),
      ('Khoe điểm tốt', 'showing good grades to parents', '💯',
        array['sticker-136', 'sticker-137', 'sticker-138'],
        'Mom, look at my test!', 'Trẻ gọi mẹ/bố xem bài kiểm tra.',
        'I got an A in Math.', 'Trẻ khoe điểm môn học (Math / English).',
        'The test was very easy.', 'Trẻ nói bài kiểm tra rất dễ (very easy / fun).',
        'Can we go to the park to celebrate?', 'Trẻ rủ đi chơi công viên để ăn mừng.',
        'Yay! Thank you, Mom!', 'Trẻ reo lên vui sướng và cảm ơn.'),
      ('Trồng cây trong vườn', 'planting a tree in the garden', '🌱',
        array['sticker-139', 'sticker-140', 'sticker-141'],
        'Can we plant a tree today?', 'Trẻ rủ bố/mẹ/bạn trồng cây.',
        'I want to plant an apple tree.', 'Trẻ nói loại cây muốn trồng (apple tree / flower).',
        'I will dig a hole here.', 'Trẻ nói sẽ đào một cái hố nhỏ.',
        'Can you give me some water, please?', 'Trẻ nhờ lấy nước để tưới cây.',
        'Grow tall, little tree!', 'Trẻ nói chuyện với cây, chúc cây mau lớn.'),
      ('Đi khám răng', 'visiting the dentist', '🦷',
        array['sticker-142', 'sticker-143', 'sticker-144'],
        'Hello, doctor!', 'Trẻ chào nha sĩ.',
        'I brush my teeth every day.', 'Trẻ tự hào kể ngày nào cũng đánh răng.',
        'Ah! Open wide!', 'Trẻ làm theo lời bác sĩ, há to miệng để kiểm tra.',
        'No cavities? That is great!', 'Trẻ vui mừng khi biết không bị sâu răng.',
        'Thank you, doctor! Goodbye!', 'Trẻ cảm ơn nha sĩ và chào tạm biệt.'),
      ('Gọi điện thoại cho ông bà', 'calling grandparents', '☎️',
        array['sticker-145', 'sticker-146', 'sticker-147'],
        'Hello, Grandma! It''s me.', 'Trẻ vui mừng chào ông/bà qua điện thoại.',
        'How are you today?', 'Trẻ hỏi thăm sức khỏe ông bà.',
        'I drew a beautiful picture for you.', 'Trẻ khoe đã vẽ một bức tranh đẹp tặng ông bà.',
        'When will you come to visit us?', 'Trẻ hỏi khi nào ông bà sẽ đến chơi.',
        'I miss you. Goodbye!', 'Trẻ nói nhớ ông bà và chào tạm biệt.'),
      ('Đi dã ngoại ở công viên', 'going for a picnic', '🧺',
        array['sticker-148', 'sticker-149', 'sticker-150'],
        'The weather is so nice today!', 'Trẻ vui mừng nói về thời tiết đẹp.',
        'Let''s have a picnic in the park.', 'Trẻ rủ bố mẹ/bạn đi dã ngoại ở công viên.',
        'I will bring sandwiches and apples.', 'Trẻ kể tên đồ ăn mang theo (sandwiches / apples / juice).',
        'Can we bring the kite too?', 'Trẻ xin mang thêm đồ chơi (kite / ball).',
        'This is the best picnic ever!', 'Trẻ vui sướng khen ngợi buổi dã ngoại.'),
      ('Thăm ông bà ở nông trại', 'visiting grandparents on the farm', '🚜',
        array['sticker-151', 'sticker-152', 'sticker-153'],
        'Hello Grandpa! I miss you.', 'Trẻ chào ông bà và nói nhớ ông bà.',
        'Where are the chickens?', 'Trẻ hỏi thăm vị trí các con vật ở nông trại.',
        'Can I feed them, please?', 'Trẻ xin phép được cho các con vật ăn.',
        'Look! They are eating so fast.', 'Trẻ ngạc nhiên khi thấy con vật ăn nhanh.',
        'I love the farm! Thank you, Grandpa.', 'Trẻ nói yêu nông trại và cảm ơn ông.'),
      ('Đi cắm trại trong rừng', 'going camping in the forest', '⛺',
        array['sticker-154', 'sticker-155', 'sticker-156'],
        'Wow, the forest is so big!', 'Trẻ ngạc nhiên trước khung cảnh khu rừng.',
        'I will help you set up the tent.', 'Trẻ chủ động đề nghị giúp bố mẹ dựng lều.',
        'Can we make a campfire now?', 'Trẻ xin phép đốt lửa trại.',
        'I want to roast marshmallows.', 'Trẻ nói muốn nướng kẹo dẻo.',
        'This is the best camping trip!', 'Trẻ bày tỏ sự vui thích với chuyến đi cắm trại.'),
      ('Chơi trốn tìm', 'playing hide and seek', '🙈',
        array['sticker-157', 'sticker-158', 'sticker-159'],
        'Let''s play hide and seek!', 'Trẻ rủ bạn cùng chơi trốn tìm.',
        'I will count to ten.', 'Trẻ xung phong làm người đếm (count to ten / close my eyes).',
        'One, two, three... Ready or not, here I come!', 'Trẻ đếm và báo hiệu bắt đầu đi tìm.',
        'I found you under the table!', 'Trẻ reo lên khi tìm thấy bạn (under the table / behind the door).',
        'That was fun! Now it''s your turn to count.', 'Trẻ khen trò chơi vui và nhường lượt đếm cho bạn.'),
      ('Giúp mẹ dọn dẹp đồ chơi', 'helping mom clean up toys', '🧸',
        array['sticker-160', 'sticker-161', 'sticker-162'],
        'Mom, can I help you?', 'Trẻ chủ động xin giúp đỡ mẹ.',
        'I will put away my blocks.', 'Trẻ nói đồ vật mình sẽ cất (blocks / cars / dolls).',
        'Where should I put this teddy bear?', 'Trẻ hỏi mẹ vị trí cất món đồ chơi.',
        'Look! The room is clean now.', 'Trẻ tự hào khoe phòng đã được dọn sạch sẽ.',
        'I am a good helper!', 'Trẻ vui vẻ tự khen ngợi bản thân ngoan ngoãn.'),
      ('Tập đi xe đạp', 'learning to ride a bike', '🚲',
        array['sticker-163', 'sticker-164', 'sticker-165'],
        'Mom, please hold my bike.', 'Trẻ nhờ mẹ/bố giữ xe đạp giúp mình.',
        'I am ready. You can push me.', 'Trẻ báo hiệu đã sẵn sàng để được đẩy đi.',
        'Don''t let go yet!', 'Trẻ lo lắng nhắc mẹ/bố khoan buông tay.',
        'Look at me! I am riding!', 'Trẻ vui mừng khoe mình đã tự đạp xe được.',
        'This is so much fun. Thank you!', 'Trẻ nói trò chơi rất vui và cảm ơn mẹ/bố đã dạy.'),
      ('Giúp người già qua đường', 'helping an elderly person cross the street', '👵',
        array['sticker-166', 'sticker-167', 'sticker-168'],
        'Hello! Do you need some help?', 'Trẻ lịch sự chào hỏi và đề nghị giúp đỡ.',
        'I can help you cross the street.', 'Trẻ chủ động ngỏ ý đưa bà/ông qua đường.',
        'Please give me your hand.', 'Trẻ dắt tay người già để cùng đi qua đường.',
        'The light is green now. Let''s go.', 'Trẻ quan sát đèn giao thông và báo hiệu có thể đi.',
        'You are welcome. Have a nice day!', 'Trẻ đáp lại lời cảm ơn và chúc người già một ngày tốt lành.'),
      ('Nhờ mẹ dạy làm bánh sandwich', 'making a sandwich', '🥪',
        array['sticker-169', 'sticker-170', 'sticker-171'],
        'Mom, can you teach me how to cook?', 'Trẻ nhờ mẹ dạy nấu ăn.',
        'I want to make a sandwich.', 'Trẻ nói tên món ăn muốn làm (a sandwich / a salad).',
        'I need bread, cheese, and ham.', 'Trẻ kể tên nguyên liệu cần dùng (bread / cheese / tomato).',
        'Look! I put the cheese on the bread.', 'Trẻ khoe thao tác mình đang làm.',
        'It is yummy! Thank you, Mom!', 'Trẻ nếm thử, khen món ăn ngon và cảm ơn mẹ.'),
      ('Kể về một giấc mơ', 'telling a dream', '😴',
        array['sticker-172', 'sticker-173', 'sticker-174'],
        'Dad, I had a funny dream last night.', 'Trẻ kể với bố/mẹ về một giấc mơ hài hước.',
        'I was flying in the sky.', 'Trẻ kể hành động trong giấc mơ (flying in the sky / swimming in the sea).',
        'I saw a pink elephant.', 'Trẻ kể thấy con vật/đồ vật kỳ lạ (a pink elephant / a talking dog).',
        'It was eating ice cream.', 'Trẻ miêu tả chi tiết hành động của con vật đó.',
        'Then I woke up. It was so funny!', 'Trẻ kết thúc câu chuyện và bày tỏ cảm xúc vui vẻ.'),
      ('Nhờ bạn dạy chơi cờ', 'asking a friend to teach a game', '♟️',
        array['sticker-175', 'sticker-176', 'sticker-177'],
        'Can you teach me how to play chess?', 'Trẻ nhờ bạn dạy chơi cờ vua (hoặc board game).',
        'How does the horse move?', 'Trẻ hỏi luật chơi cụ thể (cách di chuyển của một quân cờ).',
        'Is it my turn now?', 'Trẻ hỏi đã đến lượt mình đi chưa.',
        'Oh no, I made a mistake.', 'Trẻ nhận ra mình đi sai một nước cờ.',
        'That was a good game! Thanks!', 'Trẻ khen ván cờ hay và cảm ơn bạn đã dạy.'),
      ('Xin lỗi mẹ vì làm vỡ đồ', 'apologizing for breaking something', '🥛',
        array['sticker-178', 'sticker-179', 'sticker-180'],
        'Mom, I am so sorry.', 'Trẻ chủ động nói lời xin lỗi mẹ.',
        'I broke the blue cup.', 'Trẻ thú nhận lỗi lầm (làm vỡ chiếc cốc màu xanh / cái đĩa).',
        'It slipped from my hand.', 'Trẻ giải thích nguyên nhân khách quan (do trượt tay).',
        'I will be more careful next time.', 'Trẻ hứa lần sau sẽ cẩn thận hơn.',
        'Can I help you clean it up?', 'Trẻ xin giúp mẹ dọn dẹp các mảnh vỡ.'),
      ('Hỏi thăm giờ giấc', 'asking for the time', '⌚',
        array['sticker-181', 'sticker-182', 'sticker-183'],
        'Excuse me, what time is it?', 'Trẻ lịch sự hỏi giờ một người xung quanh.',
        'Oh, it is eight o''clock already!', 'Trẻ lặp lại giờ vừa nghe và tỏ ra ngạc nhiên.',
        'I need to go to school now.', 'Trẻ báo hiệu mình phải đi học (hoặc về nhà).',
        'My bus is coming.', 'Trẻ thấy xe buýt của mình sắp tới.',
        'Thank you for your help. Goodbye!', 'Trẻ cảm ơn người đã chỉ giờ và chào tạm biệt.'),
      ('Khen ngợi bức tranh của bạn', 'praising a friend''s drawing', '🎨',
        array['sticker-184', 'sticker-185', 'sticker-186'],
        'Wow, what a beautiful picture!', 'Trẻ ngạc nhiên khen ngợi bức tranh đẹp.',
        'Is that a dinosaur?', 'Trẻ hỏi đoán xem con vật trong tranh là gì.',
        'I really like the green color.', 'Trẻ nói màu sắc mà mình thích nhất trong tranh.',
        'You are a great artist.', 'Trẻ khen ngợi tài năng vẽ của bạn.',
        'Can you draw one for me, please?', 'Trẻ xin bạn vẽ tặng mình một bức tranh tương tự.'),
      ('Xin chơi chung thể thao', 'asking to join a game', '⚽',
        array['sticker-187', 'sticker-188', 'sticker-189'],
        'Hi everyone! What are you playing?', 'Trẻ chào các bạn và hỏi các bạn đang chơi trò gì.',
        'Can I play with you, please?', 'Trẻ xin phép được tham gia chơi cùng.',
        'I am very fast.', 'Trẻ khoe một thế mạnh của mình để được vào đội.',
        'Pass the ball to me!', 'Trẻ gọi các bạn chuyền bóng cho mình.',
        'Goal! We are the best team!', 'Trẻ reo lên khi ghi bàn và khen ngợi tinh thần đồng đội.'),
      ('Mời bạn đến nhà chơi', 'inviting a friend over to play', '🏠',
        array['sticker-190', 'sticker-191', 'sticker-192'],
        'Hi! Do you want to come to my house?', 'Trẻ rủ bạn tới nhà mình chơi.',
        'We can play with my legos.', 'Trẻ gợi ý một món đồ chơi sẽ chơi cùng nhau (legos / dolls).',
        'My mom has some cookies.', 'Trẻ khoe ở nhà có đồ ăn ngon để dụ dỗ bạn.',
        'You can come on Sunday morning.', 'Trẻ chốt thời gian hẹn gặp bạn.',
        'Great! See you on Sunday!', 'Trẻ vui mừng khi bạn đồng ý và chào tạm biệt.'),
      ('Thả diều trên cánh đồng', 'flying a kite in the field', '🪁',
        array['sticker-193', 'sticker-194', 'sticker-195'],
        'Look, the wind is very strong today.', 'Trẻ nhận xét thời tiết có gió lớn rất thích hợp.',
        'Let''s fly my new kite!', 'Trẻ hào hứng rủ bạn/người lớn cùng đi thả diều.',
        'Can you help me hold it, please?', 'Trẻ nhờ người lớn cầm giúp thân diều để chuẩn bị chạy.',
        'Wow, it is flying so high in the sky!', 'Trẻ reo lên vui sướng khi con diều đã bay cao.',
        'This is so fun!', 'Trẻ bày tỏ niềm vui với trò chơi.'),
      ('Xây lâu đài cát trên bãi biển', 'building a sandcastle at the beach', '🏖️',
        array['sticker-196', 'sticker-197', 'sticker-198'],
        'The beach is so beautiful!', 'Trẻ vui mừng khen ngợi bãi biển đẹp.',
        'Let''s build a big sandcastle.', 'Trẻ rủ bố/mẹ cùng xây một lâu đài cát lớn.',
        'I need my bucket and shovel.', 'Trẻ gọi tên các dụng cụ cần thiết (xô và xẻng).',
        'Can you get some water, please?', 'Trẻ nhờ bố/mẹ lấy giúp một ít nước biển để làm ẩm cát.',
        'Our castle looks amazing!', 'Trẻ tự hào ngắm nhìn thành quả lâu đài cát.'),
      ('Thăm bảo tàng khủng long', 'visiting a dinosaur museum', '🦖',
        array['sticker-199', 'sticker-200', 'sticker-201'],
        'Wow, this dinosaur skeleton is huge!', 'Trẻ kinh ngạc trước bộ xương khủng long khổng lồ.',
        'Is it a T-Rex?', 'Trẻ tò mò hỏi xem đây có phải là khủng long bạo chúa không.',
        'Look at its sharp teeth!', 'Trẻ chỉ vào những chiếc răng nhọn và miêu tả.',
        'Can we take a picture here?', 'Trẻ xin phép được chụp một bức ảnh kỷ niệm.',
        'I love learning about dinosaurs.', 'Trẻ nói rất thích việc tìm hiểu về khủng long.'),
      ('Nhận bưu kiện từ người giao hàng', 'receiving a package from a delivery person', '📦',
        array['sticker-202', 'sticker-203', 'sticker-204'],
        'Hello, are you the delivery man?', 'Trẻ ra mở cửa và chào hỏi chú giao hàng.',
        'Is this package for my mom?', 'Trẻ hỏi xác nhận xem món hàng có phải của mẹ không.',
        'Can I take it, please?', 'Trẻ ngoan ngoãn xin phép được cầm hộp hàng vào nhà.',
        'Oh, it is very heavy.', 'Trẻ nhận xét món hàng khá nặng khi cầm lên.',
        'Thank you for the delivery. Have a good day!', 'Trẻ cảm ơn và chúc chú giao hàng một ngày tốt lành.'),
      ('Làm thiệp tặng mẹ', 'making a card for Mom', '💌',
        array['sticker-205', 'sticker-206', 'sticker-207'],
        'Dad, I want to make a card for Mom.', 'Trẻ nói với bố về ý định làm một tấm thiệp tặng mẹ.',
        'Can you give me the pink paper?', 'Trẻ nhờ bố đưa giúp tờ giấy màu hồng.',
        'I will draw a big heart on it.', 'Trẻ miêu tả hình ảnh mình định vẽ (một trái tim lớn).',
        'How do you spell ''I love you''?', 'Trẻ hỏi bố cách đánh vần dòng chữ yêu thương.',
        'Mom will be very happy!', 'Trẻ tin tưởng và vui vẻ nghĩ đến lúc mẹ nhận thiệp.'),
      ('Ngắm sao bằng kính viễn vọng', 'looking at stars through a telescope', '🔭',
        array['sticker-208', 'sticker-209', 'sticker-210'],
        'Look, the sky is very clear tonight.', 'Trẻ nhận xét bầu trời đêm nay rất quang đãng.',
        'Can I use the telescope, please?', 'Trẻ xin phép được sử dụng kính viễn vọng.',
        'I want to see the moon.', 'Trẻ nói mục tiêu muốn ngắm nhìn là mặt trăng.',
        'Wow, it is so big and bright!', 'Trẻ ngạc nhiên khi thấy mặt trăng to và sáng qua thấu kính.',
        'I can see many stars too. Thank you!', 'Trẻ khoe thấy cả những vì sao và cảm ơn bố/mẹ.'),
      ('Làm người tuyết', 'building a snowman', '⛄',
        array['sticker-211', 'sticker-212', 'sticker-213'],
        'Yay! It is snowing outside!', 'Trẻ reo lên vui sướng khi thấy tuyết rơi ngoài trời.',
        'Let''s build a big snowman.', 'Trẻ rủ bạn/người lớn ra ngoài đắp một người tuyết to.',
        'I will make the head.', 'Trẻ phân công nhiệm vụ và nhận làm phần đầu người tuyết.',
        'We need a carrot for the nose.', 'Trẻ nhắc cần lấy một củ cà rốt để làm mũi.',
        'He looks very funny! I love winter.', 'Trẻ bật cười vì vẻ ngoài buồn cười của người tuyết và nói yêu mùa đông.'),
      ('Đi tàu lượn siêu tốc', 'riding a rollercoaster', '🎢',
        array['sticker-214', 'sticker-215', 'sticker-216'],
        'I want to ride the rollercoaster, please.', 'Trẻ đề nghị bố/mẹ cho chơi tàu lượn siêu tốc.',
        'Am I tall enough to ride it?', 'Trẻ tự giác hỏi nhân viên soát vé xem mình đã đủ chiều cao chưa.',
        'I will sit in the front.', 'Trẻ chọn vị trí ngồi ở hàng ghế đầu tiên.',
        'Hold on tight! Here we go!', 'Trẻ nhắc nhở bám chặt khi tàu chuẩn bị khởi hành.',
        'That was so fast and fun!', 'Trẻ hét lên phấn khích khi chuyến đi kết thúc.'),
      ('Gói quà sinh nhật', 'wrapping a birthday gift', '🎁',
        array['sticker-217', 'sticker-218', 'sticker-219'],
        'Dad, let''s wrap the gift for my friend.', 'Trẻ gọi bố cùng đóng gói quà tặng sinh nhật cho bạn.',
        'I choose the blue paper.', 'Trẻ chọn giấy bọc quà màu xanh.',
        'Can you cut the tape, please?', 'Trẻ nhờ bố cắt giúp một mẩu băng dính.',
        'I will tie a red ribbon on it.', 'Trẻ tự tay thắt một chiếc nơ ruy-băng màu đỏ lên hộp quà.',
        'It looks beautiful! Let''s go to the party.', 'Trẻ ngắm hộp quà đẹp mắt và hối thúc đi dự tiệc.'),
      ('Thu hoạch táo ở trang trại', 'picking apples at an orchard', '🍎',
        array['sticker-220', 'sticker-221', 'sticker-222'],
        'There are so many apples here!', 'Trẻ reo lên khi thấy vườn có rất nhiều quả táo.',
        'I want to pick the red ones.', 'Trẻ nói muốn ưu tiên hái những quả táo màu đỏ chín mọng.',
        'Can you help me reach that high apple, please?', 'Trẻ nhờ người lớn lấy giúp quả táo trên cành cao.',
        'I will put it in my basket.', 'Trẻ cẩn thận đặt quả táo vừa hái vào chiếc giỏ của mình.',
        'Let''s go home and make an apple pie!', 'Trẻ rủ về nhà làm bánh nướng nhân táo từ thành quả vừa thu hoạch.'),
      ('Trang trí cây thông Noel', 'decorating a Christmas tree', '🎄',
        array['sticker-223', 'sticker-224', 'sticker-225'],
        'Christmas is coming soon!', 'Trẻ vui mừng nhắc nhở giáng sinh sắp đến.',
        'Let''s decorate the Christmas tree.', 'Trẻ rủ bố/mẹ bắt tay vào trang trí cây thông.',
        'I will put the star on the top.', 'Trẻ xung phong gắn ngôi sao lên đỉnh cây thông.',
        'Can you give me the red balls, please?', 'Trẻ nhờ bố/mẹ đưa những quả châu màu đỏ.',
        'The tree looks so beautiful!', 'Trẻ ngắm nhìn và khen ngợi cây thông đã được trang trí xong.'),
      ('Mua hoa tặng cô giáo', 'buying flowers for the teacher', '💐',
        array['sticker-226', 'sticker-227', 'sticker-228'],
        'Hello, I want to buy some flowers, please.', 'Trẻ chào người bán hoa và nói ý định mua.',
        'It is for my teacher.', 'Trẻ tiết lộ người nhận hoa là cô giáo.',
        'I want the yellow sunflowers.', 'Trẻ chỉ định chọn hoa hướng dương màu vàng.',
        'Can you wrap them in pink paper?', 'Trẻ yêu cầu gói hoa bằng giấy màu hồng.',
        'They look very nice. Thank you!', 'Trẻ hài lòng khen bó hoa đẹp và cảm ơn.'),
      ('Tham gia lớp học võ', 'joining a martial arts class', '🥋',
        array['sticker-229', 'sticker-230', 'sticker-231'],
        'Hello, Master. I am ready to learn.', 'Trẻ cúi chào thầy giáo và báo cáo đã sẵn sàng.',
        'Look at my new white belt.', 'Trẻ tự hào khoe chiếc đai trắng mới của mình.',
        'How do I kick high?', 'Trẻ nhờ thầy hướng dẫn cách đá chân lên cao.',
        'Hiyah! I did it!', 'Trẻ hô to khẩu quyết võ thuật khi thực hiện thành công động tác.',
        'Thank you, Master. I will practice at home.', 'Trẻ cảm ơn thầy và hứa sẽ luyện tập thêm ở nhà.'),
      ('Tham quan thủy cung', 'visiting an aquarium', '🐠',
        array['sticker-232', 'sticker-233', 'sticker-234'],
        'Wow, there are so many fishes here!', 'Trẻ ngạc nhiên trước số lượng cá phong phú trong thủy cung.',
        'Look at that big shark!', 'Trẻ chỉ tay và gọi bạn/bố mẹ nhìn con cá mập lớn.',
        'Does it eat small fishes?', 'Trẻ tò mò hỏi xem cá mập có ăn cá nhỏ không.',
        'I like the little turtles.', 'Trẻ chỉ vào rùa biển và nói mình thích chúng.',
        'The aquarium is amazing!', 'Trẻ thể hiện sự thích thú với chuyến đi tham quan.'),
      ('Đi xem xiếc', 'watching a circus show', '🎪',
        array['sticker-235', 'sticker-236', 'sticker-237'],
        'The circus is so big and noisy!', 'Trẻ nhận xét về không khí nhộn nhịp, hoành tráng của rạp xiếc.',
        'Look at the funny clown!', 'Trẻ chỉ vào chú hề ngộ nghĩnh và gọi mọi người xem.',
        'He is juggling three balls.', 'Trẻ miêu tả hành động tung hứng của chú hề.',
        'Now the lions are coming out.', 'Trẻ thông báo khi tiết mục của những chú sư tử bắt đầu.',
        'I love the circus show! Let''s clap our hands.', 'Trẻ bày tỏ sự yêu thích và rủ mọi người vỗ tay tán thưởng.'),
      ('Rửa xe ô tô cùng bố', 'washing the car with Dad', '🚗',
        array['sticker-238', 'sticker-239', 'sticker-240'],
        'Dad, the car is very dirty.', 'Trẻ chỉ cho bố thấy chiếc xe đang rất bẩn.',
        'Can I help you wash it, please?', 'Trẻ xin phép được phụ bố rửa xe.',
        'I need a sponge and some soap.', 'Trẻ gọi tên các vật dụng cần thiết (miếng bọt biển và xà phòng).',
        'Look at all the bubbles!', 'Trẻ thích thú kêu lên khi thấy rất nhiều bọt xà phòng.',
        'The car is so clean and shiny now!', 'Trẻ tự hào ngắm nhìn chiếc xe sạch bóng sau khi rửa xong.'),
      ('Học làm bánh quy', 'learning to bake cookies', '🍪',
        array['sticker-241', 'sticker-242', 'sticker-243'],
        'Mom, can we bake cookies today?', 'Trẻ rủ mẹ cùng nướng bánh quy.',
        'I will mix the flour and sugar.', 'Trẻ xung phong trộn các nguyên liệu cơ bản (bột mì và đường).',
        'Can I add the chocolate chips, please?', 'Trẻ xin phép được rắc hạt sô-cô-la vào bột.',
        'They smell so good in the oven.', 'Trẻ nhận xét mùi thơm của bánh khi đang nướng trong lò.',
        'I want to eat them with milk. Yummy!', 'Trẻ háo hức muốn ăn bánh cùng với sữa.'),
      ('Tham gia tiệc hóa trang', 'going to a costume party', '👻',
        array['sticker-244', 'sticker-245', 'sticker-246'],
        'Are you ready for the costume party?', 'Trẻ hỏi xem bạn/anh chị đã sẵn sàng đi dự tiệc hóa trang chưa.',
        'I am wearing my pirate costume.', 'Trẻ khoe mình đang mặc trang phục cướp biển.',
        'Where is my pirate hat?', 'Trẻ tìm kiếm phụ kiện (chiếc mũ cướp biển) còn thiếu.',
        'You look like a scary ghost!', 'Trẻ nhận xét trang phục của bạn (giống một con ma đáng sợ).',
        'Let''s go and get some candies!', 'Trẻ hào hứng rủ bạn đi xin kẹo.'),
      ('Tập trượt patin', 'learning to roller skate', '🛼',
        array['sticker-247', 'sticker-248', 'sticker-249'],
        'I want to try my new roller skates.', 'Trẻ bày tỏ mong muốn được đi thử đôi giày trượt patin mới.',
        'Can you hold my hand, please?', 'Trẻ nhờ bố/mẹ nắm tay để giữ thăng bằng.',
        'I am going very slowly.', 'Trẻ cho biết mình đang trượt rất chậm rãi và cẩn thận.',
        'Oops, I fell down!', 'Trẻ thốt lên khi bị vấp ngã.',
        'I am okay. I will try again!', 'Trẻ dũng cảm đứng lên, báo mình không sao và muốn thử lại.'),
      ('Bắt bướm ở đồng cỏ', 'catching butterflies in the meadow', '🦋',
        array['sticker-250', 'sticker-251', 'sticker-252'],
        'The meadow is full of beautiful flowers.', 'Trẻ khen ngợi cánh đồng cỏ có rất nhiều hoa đẹp.',
        'Look! There is a yellow butterfly.', 'Trẻ phát hiện và chỉ cho mọi người một con bướm màu vàng.',
        'I will catch it with my net.', 'Trẻ nói sẽ dùng chiếc vợt của mình để bắt bướm.',
        'Be quiet, it is flying away.', 'Trẻ nhắc nhở giữ trật tự để bướm không bay mất.',
        'I caught it! Let''s let it go now.', 'Trẻ reo lên khi bắt được bướm, sau đó rủ thả bướm bay đi.'),
      ('Mua truyện tranh ở nhà sách', 'buying comic books at the bookstore', '📚',
        array['sticker-253', 'sticker-254', 'sticker-255'],
        'Wow, this bookstore has so many books!', 'Trẻ ngạc nhiên vì nhà sách có quá nhiều sách.',
        'I am looking for the superhero comic.', 'Trẻ nói mục đích muốn tìm mua cuốn truyện tranh siêu anh hùng.',
        'Oh, here it is on the top shelf.', 'Trẻ phát hiện ra cuốn truyện nằm ở trên kệ cao.',
        'Can you buy this for me, Mom?', 'Trẻ xin mẹ mua cuốn truyện tranh đó cho mình.',
        'Thank you! I will read it tonight.', 'Trẻ cảm ơn và hứa sẽ đọc truyện ngay tối nay.'),
      ('Câu cá cùng ông nội', 'fishing with Grandpa', '🎣',
        array['sticker-256', 'sticker-257', 'sticker-258'],
        'Grandpa, the lake is so quiet today.', 'Trẻ nhận xét mặt hồ hôm nay rất yên tĩnh.',
        'Can you help me put the bait on the hook?', 'Trẻ nhờ ông mắc mồi vào lưỡi câu giúp mình.',
        'I will throw the line into the water.', 'Trẻ thông báo hành động ném dây câu xuống nước.',
        'Look! The float is moving!', 'Trẻ kích động chỉ cho ông thấy chiếc phao đang nhấp nhô.',
        'I caught a big fish! I am so happy!', 'Trẻ reo mừng rỡ khi tự tay câu được một con cá lớn.'),
      ('Gấp thuyền giấy', 'folding paper boats', '⛵',
        array['sticker-259', 'sticker-260', 'sticker-261'],
        'It is raining outside.', 'Trẻ thông báo trời đang mưa ở bên ngoài.',
        'Let''s fold some paper boats!', 'Trẻ rủ anh/chị hoặc bố/mẹ cùng gấp thuyền giấy.',
        'I am making a red boat.', 'Trẻ cho biết mình đang làm một chiếc thuyền màu đỏ.',
        'Let''s put them in the water.', 'Trẻ rủ mang những chiếc thuyền giấy ra thả vào vũng nước.',
        'Look at my boat, it is floating so fast!', 'Trẻ phấn khích chỉ vào chiếc thuyền của mình đang trôi rất nhanh.'),
      ('Tham gia cuộc thi vẽ tranh', 'joining a drawing contest', '🎨',
        array['sticker-262', 'sticker-263', 'sticker-264'],
        'I am so excited for the drawing contest.', 'Trẻ bày tỏ sự háo hức trước cuộc thi vẽ tranh.',
        'I will draw a beautiful rainbow.', 'Trẻ quyết định sẽ vẽ một chiếc cầu vồng thật đẹp.',
        'I need my color pencils, please.', 'Trẻ gọi hỏi xin hộp bút chì màu của mình.',
        'I am coloring the sun yellow.', 'Trẻ miêu tả hành động đang tô màu vàng cho mặt trời.',
        'I finished! I hope I can win.', 'Trẻ thông báo đã vẽ xong và hy vọng mình sẽ đoạt giải.'),
      ('Dựng lều bằng chăn trong phòng khách', 'building a blanket fort', '⛺',
        array['sticker-265', 'sticker-266', 'sticker-267'],
        'Let''s build a fort in the living room!', 'Trẻ rủ rê dựng một túp lều ngay trong phòng khách.',
        'We need some pillows and a big blanket.', 'Trẻ liệt kê các vật dụng cần thiết: những chiếc gối và một cái chăn lớn.',
        'Can you put the blanket over the chairs?', 'Trẻ nhờ bố/mẹ phủ chiếc chăn qua những cái ghế để tạo mái lều.',
        'It is so dark inside. I need a flashlight.', 'Trẻ nói bên trong hơi tối và cần một chiếc đèn pin.',
        'Our fort is so cozy! Let''s read a book here.', 'Trẻ khen túp lều thật ấm cúng và rủ đọc sách bên trong.'),
      ('Làm lồng đèn Trung Thu', 'making a Mid-Autumn lantern', '🏮',
        array['sticker-268', 'sticker-269', 'sticker-270'],
        'Mid-Autumn Festival is coming.', 'Trẻ thông báo tết Trung Thu đang đến gần.',
        'Let''s make a star lantern, Dad.', 'Trẻ rủ bố cùng làm một chiếc lồng đèn hình ngôi sao.',
        'I need some bamboo sticks and red paper.', 'Trẻ liệt kê vật liệu cần thiết: thanh tre và giấy kiếng đỏ.',
        'Can you help me glue the paper, please?', 'Trẻ nhờ bố dán giấy kiếng lên khung lồng đèn.',
        'My lantern is so bright. Let''s go out and play!', 'Trẻ khen lồng đèn sáng và rủ ra ngoài rước đèn.'),
      ('Xem múa lân', 'watching a lion dance', '🦁',
        array['sticker-271', 'sticker-272', 'sticker-273'],
        'Listen! I hear the drums outside.', 'Trẻ thu hút sự chú ý khi nghe tiếng trống hội bên ngoài.',
        'Let''s go and watch the lion dance.', 'Trẻ rủ mọi người cùng ra xem múa lân.',
        'Wow, the red lion is jumping so high.', 'Trẻ ngạc nhiên khen ngợi chú lân màu đỏ nhảy rất cao.',
        'It is eating the cabbage.', 'Trẻ miêu tả động tác lân "ăn" bắp cải (hái lộc).',
        'That was an amazing show!', 'Trẻ vỗ tay và khen ngợi màn biểu diễn rất tuyệt vời.'),
      ('Lạc đường trong siêu thị', 'getting lost in the supermarket', '🛒',
        array['sticker-274', 'sticker-275', 'sticker-276'],
        'Mom, where are you? I cannot find you.', 'Trẻ hốt hoảng nhận ra mình bị lạc mất mẹ.',
        'I will go to the security guard.', 'Trẻ bình tĩnh quyết định tìm đến chú bảo vệ để nhờ giúp đỡ.',
        'Hello sir, I am lost.', 'Trẻ chủ động chào và thông báo tình trạng đi lạc của mình.',
        'My mom''s name is Mary. She is wearing a blue shirt.', 'Trẻ cung cấp thông tin mô tả để tìm mẹ (tên và màu áo).',
        'Thank you for helping me find my mom!', 'Trẻ cảm ơn chú bảo vệ sau khi đã gặp lại được mẹ.'),
      ('Làm thủ tục ở sân bay', 'checking in at the airport', '✈️',
        array['sticker-277', 'sticker-278', 'sticker-279'],
        'Hello, we want to check in for our flight.', 'Trẻ thay mặt bố mẹ chào và nói muốn làm thủ tục chuyến bay.',
        'Here are our passports.', 'Trẻ lịch sự đưa hộ chiếu cho nhân viên quầy.',
        'Can I have a window seat, please?', 'Trẻ ngoan ngoãn xin một chỗ ngồi cạnh cửa sổ.',
        'I will put my suitcase on the scale.', 'Trẻ chủ động nhấc vali của mình lên bàn cân hành lý.',
        'Thank you! Let''s go to the airplane.', 'Trẻ nhận lại giấy tờ, cảm ơn và háo hức lên máy bay.'),
      ('Tắm cho cún con', 'bathing the puppy', '🐶',
        array['sticker-280', 'sticker-281', 'sticker-282'],
        'Oh no, the puppy is covered in mud.', 'Trẻ hoảng hốt khi thấy cún con dính đầy bùn đất.',
        'Let''s give him a bath in the tub.', 'Trẻ đề nghị mang cún vào bồn tắm để làm sạch.',
        'I will gently pour warm water on him.', 'Trẻ nói sẽ nhẹ nhàng giội nước ấm lên người cún.',
        'Now let''s use the dog shampoo.', 'Trẻ nhắc lấy sữa tắm chuyên dụng dành cho chó.',
        'He is shaking the water off! So funny!', 'Trẻ bật cười nắc nẻ khi thấy chú cún lắc mình văng tung tóe nước.'),
      ('Đi khám mắt', 'getting an eye exam', '👓',
        array['sticker-283', 'sticker-284', 'sticker-285'],
        'Hello doctor, my eyes are blurry.', 'Trẻ chào bác sĩ và trình bày triệu chứng (mắt bị mờ).',
        'I cannot read the letters on the board.', 'Trẻ phàn nàn không thể đọc được chữ trên bảng đo thị lực.',
        'I will read the big letter A.', 'Trẻ cố gắng đọc chữ cái lớn nhất theo yêu cầu của bác sĩ.',
        'Do I need to wear glasses?', 'Trẻ lo lắng hỏi xem mình có phải đeo kính không.',
        'I choose the blue glasses frame. Thank you!', 'Trẻ vui vẻ chọn gọng kính màu xanh dương và cảm ơn bác sĩ.'),
      ('Tô tượng', 'painting plaster statues', '🖌️',
        array['sticker-286', 'sticker-287', 'sticker-288'],
        'I want to paint a statue, please.', 'Trẻ lễ phép hỏi người bán hàng để mua tượng tô màu.',
        'I choose the Pikachu statue.', 'Trẻ nói quyết định chọn bức tượng hình Pikachu.',
        'Can I have some yellow and red paint?', 'Trẻ xin màu vẽ cần thiết (màu vàng và màu đỏ).',
        'I will paint the cheeks red.', 'Trẻ miêu tả hành động đang tô màu đỏ cho đôi má của bức tượng.',
        'My Pikachu looks so cute!', 'Trẻ tự hào khen ngợi thành phẩm của mình trông rất đáng yêu.'),
      ('Thăm quan trạm cứu hỏa', 'visiting a fire station', '🚒',
        array['sticker-289', 'sticker-290', 'sticker-291'],
        'Wow, the fire truck is so big and red!', 'Trẻ kinh ngạc khen ngợi chiếc xe cứu hỏa to và đỏ rực.',
        'Can I wear the firefighter''s helmet, please?', 'Trẻ xin phép chú lính cứu hỏa được đội thử mũ bảo hộ.',
        'The hose is very heavy.', 'Trẻ nhận xét vòi xịt nước cứu hỏa rất nặng khi thử nhấc lên.',
        'How loud is the siren?', 'Trẻ tò mò hỏi xem tiếng còi báo động kêu to đến mức nào.',
        'When I grow up, I want to be a firefighter!', 'Trẻ thể hiện sự ngưỡng mộ và ước mơ trở thành lính cứu hỏa.'),
      ('Xem múa rối nước', 'watching a water puppet show', '🎭',
        array['sticker-292', 'sticker-293', 'sticker-294'],
        'The stage is made of water!', 'Trẻ phát hiện điều kỳ lạ: sân khấu được làm bằng nước.',
        'Look! A wooden dragon is swimming.', 'Trẻ hào hứng chỉ con rồng gỗ đang bơi lượn trên mặt nước.',
        'How do they control the puppets?', 'Trẻ thắc mắc hỏi người lớn về cách điều khiển những con rối.',
        'The music is so traditional and fun.', 'Trẻ nhận xét âm nhạc nghe rất truyền thống và vui nhộn.',
        'I really enjoyed the water puppet show.', 'Trẻ tổng kết cảm xúc rất thích thú với buổi biểu diễn.'),
      ('Trượt tuyết bằng ván', 'going sledding in the snow', '🛷',
        array['sticker-295', 'sticker-296', 'sticker-297'],
        'The snow is very thick on the hill.', 'Trẻ nhận xét lớp tuyết trên đồi đang rất dày.',
        'Let''s slide down on my sled.', 'Trẻ rủ rê chơi trượt từ trên đồi xuống bằng ván trượt.',
        'Can you push me, Dad?', 'Trẻ nhờ bố đẩy một lực từ phía sau để lấy đà.',
        'Wheee! This is so fast!', 'Trẻ hét lên phấn khích khi ván trượt lao đi với tốc độ cao.',
        'I am covered in snow! Let''s do it again.', 'Trẻ thông báo mình dính đầy tuyết nhưng vẫn vui vẻ rủ chơi thêm lần nữa.'),
      ('Bỏ ống heo tiết kiệm', 'saving money in a piggy bank', '🐷',
        array['sticker-298', 'sticker-299', 'sticker-300'],
        'Mom, I have some extra coins.', 'Trẻ thông báo với mẹ rằng mình đang có vài đồng tiền lẻ dư.',
        'I will put them in my pink piggy bank.', 'Trẻ chủ động nói sẽ cất tiền vào con heo đất màu hồng.',
        'Listen to the sound it makes! Clink clink!', 'Trẻ bảo mẹ lắng nghe tiếng đồng xu rơi vào trong heo đất.',
        'I am saving money to buy a new bicycle.', 'Trẻ giải thích mục tiêu tiết kiệm là để mua một chiếc xe đạp mới.',
        'I will feed my piggy bank every day.', 'Trẻ hứa sẽ "cho heo ăn" tiền tiết kiệm mỗi ngày.')
    ) as t(title, topic, icon, pool, s1, i1, s2, i2, s3, i3, s4, i4, s5, i5)
  )
  loop
    if not exists (select 1 from missions where title = m.title) then
      insert into missions (id, language_id, title, topic, level, step_count, sticker_pool, icon)
      values (gen_random_uuid(), 'en', m.title, m.topic, 'beginner', 5, m.pool, m.icon)
      returning id into v_mission_id;

      insert into mission_steps (mission_id, step_order, target_sentence, intent) values
        (v_mission_id, 1, m.s1, m.i1),
        (v_mission_id, 2, m.s2, m.i2),
        (v_mission_id, 3, m.s3, m.i3),
        (v_mission_id, 4, m.s4, m.i4),
        (v_mission_id, 5, m.s5, m.i5);
    else
      -- Update sticker_pool for existing missions
      update missions
      set sticker_pool = m.pool
      where title = m.title;
    end if;
  end loop;
end $$;
